modules = [
    ("users", []), ("roles", []), ("companies", []), ("branches", []),
    ("fiscalYears", ["close", "reopen"]), ("currencies", []), ("numberSequences", []),
    ("settings", []), ("masterData", ["archive", "reorder"]),
    ("notifications", ["viewAll"]), ("executiveOversight", ["viewOwn"]),
    ("audit", []), ("approvals", ["approve"]), ("projects", []), ("phases", []),
    ("buildings", []), ("floors", []), ("units", []), ("unitTypes", []),
    ("unitStatuses", []), ("unitPriceLists", []), ("unitPricing", []),
    ("unitDiscounts", []), ("leads", []), ("leadSources", []), ("leadActivities", []),
    ("leadFollowUps", []), ("leadAssignments", []), ("leadConversions", []),
    ("customers", []), ("customerContacts", []), ("customerDocuments", []),
    ("customerNotes", []), ("reservations", []), ("reservationPayments", []),
    ("reservationNotes", []), ("reservationDocuments", []),
    ("contracts", ["submitFinance", "financeReview", "financeApprove", "financeReturn", "financeReject", "legalApprove"]),
    ("contractAmendments", []), ("contractCancellations", []), ("contractNotes", []),
    ("contractDocuments", []), ("unitTransfers", []), ("installmentPlans", []),
    ("installmentSchedules", []), ("installmentCollections", []), ("penaltyRules", []),
    ("cashboxes", []), ("treasuryTransactions", []), ("bankAccounts", []),
    ("bankTransactions", []), ("receipts", ["approve", "post", "reverse", "cancel"]),
    ("paymentVouchers", ["approve", "post", "reverse", "cancel"]),
    ("customerInvoices", ["post", "reverse", "cancel"]),
    ("supplierInvoices", ["post", "reverse", "cancel"]), ("taxCodes", []),
    ("cheques", []), ("penalties", []), ("accounts", []), ("costCenters", []),
    ("profitCenters", []), ("fiscalPeriods", ["close", "reopen"]),
    ("journalEntries", ["post", "approve", "reverse"]), ("accountMappings", []),
    ("budgets", []), ("accountingReports", ["export"]),
    ("engineeringDisciplines", []), ("consultants", []), ("designPackages", []),
    ("drawingCategories", []), ("technicalSpecifications", []),
    ("drawings", ["approve"]), ("drawingRevisions", []), ("boqs", []), ("boqItems", []),
    ("boqQuantityRevisions", []), ("costEstimates", ["approve"]),
    ("inspectionRequests", []), ("inspectionReports", []), ("defects", []),
    ("correctiveActions", ["close"]), ("rfis", ["respond", "close"]),
    ("technicalSubmittals", ["approve"]), ("materialSubmittals", ["approve"]),
    ("consultantResponses", []), ("engineeringProgress", []), ("contractors", []),
    ("contractorContracts", []), ("contractBoqItems", []), ("workProgressUpdates", []),
    ("paymentCertificates", ["approve", "verify", "submit", "review", "post", "pay", "close"]),
    ("certificateItems", []), ("certificateStatuses", []),
    ("certificateApprovals", ["approve", "reject"]), ("certificateApprovalLogs", []),
    ("variationOrders", ["approve"]), ("contractorDeductions", []), ("contractorAdditions", []),
    ("retentions", ["release"]), ("advancePayments", []), ("advanceRecoveries", ["recover"]),
    ("contractorInvoices", ["verify"]), ("contractApprovals", ["approve"]),
    ("supplierCategories", []), ("suppliers", ["blacklist"]), ("supplierContacts", []),
    ("supplierEvaluations", ["approve"]), ("purchaseRequests", ["approve"]),
    ("purchaseRequestItems", []), ("rfqs", ["issue", "close"]), ("rfqItems", []),
    ("rfqSuppliers", []), ("supplierQuotations", ["award"]), ("quotationItems", []),
    ("purchaseOrders", ["approve", "issue"]), ("purchaseOrderItems", []),
    ("purchaseContracts", ["approve"]), ("purchaseContractAmendments", ["approve"]),
    ("goodsReceiptNotes", ["inspect"]), ("grnItems", []), ("purchaseReturns", ["approve"]),
    ("purchaseReturnItems", []), ("procurementApprovals", ["approve"]),
    ("warehouses", []), ("warehouseLocations", []), ("itemCategories", []),
    ("itemGroups", []), ("unitsOfMeasure", []), ("inventoryItems", []),
    ("reorderLevels", []), ("stockOpeningBalances", []),
    ("goodsReceipts", ["complete"]), ("goodsReceiptItems", []),
    ("goodsIssues", ["complete"]), ("goodsIssueItems", []),
    ("inventoryTransfers", ["complete"]), ("inventoryTransferItems", []),
    ("stockAdjustments", ["approve"]), ("stockAdjustmentItems", []),
    ("stockCounts", ["complete"]), ("stockCountItems", []), ("inventoryLedger", []),
    ("departments", []), ("sections", []), ("jobTitles", []), ("employees", []),
    ("employeeDocuments", []), ("employeeEmergencyContacts", []), ("shifts", []),
    ("attendanceRecords", []), ("leaveTypes", []), ("leaveBalances", []),
    ("leaveRequests", ["submit", "approve", "reject"]), ("salaryComponents", []),
    ("payrollPeriods", []), ("payrollRuns", ["approve", "post", "reverse"]),
    ("payslips", []), ("payslipLines", []), ("employeeLoans", ["approve", "disburse"]),
    ("loanInstallments", []), ("employeeAdvances", ["approve", "pay"]),
    ("kpiTemplates", []), ("employeeEvaluations", []), ("employeeEvaluationLines", []),
    ("legalContracts", ["review", "approve", "activate", "suspend", "terminate", "renew", "archive"]),
    ("contractTemplates", []), ("contractVersions", []), ("legalContractAmendments", []),
    ("contractAddendums", []), ("legalContractAttachments", []), ("contractEvents", []),
    ("lawFirms", []), ("legalAdvisors", []), ("legalCases", ["close", "reopen"]),
    ("legalHearings", []), ("legalClaims", []), ("legalNotices", ["send"]),
    ("legalCaseLinks", []), ("bi", []), ("ai", []), ("crm", []), ("landParcels", []),
    ("landOwnerships", []), ("landLegalStatuses", []), ("landUtilizations", []),
    ("landDocuments", []), ("landAcquisitions", []), ("handoverRequests", []),
    ("handoverSchedules", []), ("handoverChecklistItems", []), ("handoverMinutes", []),
    ("handoverSnags", []), ("handoverApprovals", ["approve", "reject"]),
    ("slaPolicies", []), ("serviceEscalations", ["resolve"]), ("complaints", []),
    ("maintenanceRequests", []), ("supportTickets", []), ("callLogs", []),
    ("workOrders", []), ("customerSatisfactionSurveys", []), ("assetCategories", []),
    ("fixedAssets", []), ("assetTransfers", ["approve"]), ("assetDepreciations", ["post", "reverse"]),
    ("assetInventoryCounts", []), ("assetDisposals", ["approve"]), ("correspondence", []),
    ("meetings", []), ("administrativeDecisions", []), ("administrativeTasks", []),
    ("generalServices", []), ("vehicles", []), ("drivers", []), ("vehicleMissions", []),
    ("vehicleMaintenance", []), ("visitorLogs", []), ("circulars", []), ("policies", []),
    ("marketing", []), ("marketingChannels", []), ("marketingDistributionRules", []),
    ("marketingDistributionAgents", []), ("marketingDistributionLogs", []),
    ("formTemplates", ["submit", "endorse", "approve", "reject", "disable", "enable", "activate", "print"]),
    ("documents", ["submit", "endorse", "approve", "reject", "activate", "archive", "restore", "requestDelete", "viewAll"]),
    ("employeeInsurances", []), ("insuranceForms", []), ("insuranceAdditions", []),
    ("insuranceExclusions", []), ("insuranceDataAmendments", []), ("insuranceSubscriptions", []),
    ("insurancePaymentNotices", []), ("insuranceReconciliations", []),
    ("insuranceArrears", []), ("insurancePenalties", []), ("serviceTerminations", []),
    ("insuranceSettlements", []), ("insuranceClearances", []), ("subcontractorInsurances", []),
    ("projectLaborInsurances", [])
]
actions = ["view", "create", "update", "delete"]
for m, extra in modules:
    for a in actions + extra:
        print(f"{m}.{a}")
