export type Lang = "en" | "ar";

export const ENUM_LABELS: Record<string, { en: string; ar: string }> = {
  // land bank
  available: { en: "Available", ar: "متاحة" },
  acquired: { en: "Acquired", ar: "مُكتسبة" },
  under_development: { en: "Under Development", ar: "قيد التطوير" },
  developed: { en: "Developed", ar: "مطوّرة" },
  sold: { en: "Sold", ar: "مباعة" },
  freehold: { en: "Freehold", ar: "ملكية تامة" },
  leasehold: { en: "Leasehold", ar: "حق انتفاع طويل" },
  usufruct: { en: "Usufruct", ar: "حق انتفاع" },
  joint: { en: "Joint", ar: "ملكية مشتركة" },
  clear: { en: "Clear", ar: "خالية" },
  disputed: { en: "Disputed", ar: "متنازع عليها" },
  mortgaged: { en: "Mortgaged", ar: "مرهونة" },
  restricted: { en: "Restricted", ar: "مقيّدة" },
  development: { en: "Development", ar: "تطوير" },
  lease: { en: "Lease", ar: "إيجار" },
  reserve: { en: "Reserve", ar: "احتياطي" },
  planned: { en: "Planned", ar: "مخطط" },
  deed: { en: "Title Deed", ar: "صك ملكية" },
  survey: { en: "Survey", ar: "مساحة" },
  permit: { en: "Permit", ar: "تصريح" },
  valuation: { en: "Valuation", ar: "تقييم" },
  inheritance: { en: "Inheritance", ar: "ميراث" },
  grant: { en: "Grant", ar: "منحة" },
  exchange: { en: "Exchange", ar: "مبادلة" },
  cash: { en: "Cash", ar: "نقدي" },
  bank_transfer: { en: "Bank Transfer", ar: "تحويل بنكي" },
  cheque: { en: "Cheque", ar: "شيك" },
  card: { en: "Card", ar: "بطاقة" },
  active: { en: "Active", ar: "نشط" },
  inactive: { en: "Inactive", ar: "غير نشط" },
  closed: { en: "Closed", ar: "مغلق" },
  converted: { en: "Converted", ar: "محوّل" },
  cancelled: { en: "Cancelled", ar: "ملغي" },
  expired: { en: "Expired", ar: "منتهي" },
  pending: { en: "Pending", ar: "قيد الانتظار" },
  paid: { en: "Paid", ar: "مدفوع" },
  partial: { en: "Partial", ar: "جزئي" },
  partially_paid: { en: "Partially Paid", ar: "مدفوع جزئياً" },
  overdue: { en: "Overdue", ar: "متأخر" },
  waived: { en: "Waived", ar: "معفى" },
  confirmed: { en: "Confirmed", ar: "مؤكد" },
  done: { en: "Done", ar: "منجز" },
  individual: { en: "Individual", ar: "فرد" },
  company: { en: "Company", ar: "شركة" },
  fixed: { en: "Fixed", ar: "ثابت" },
  percentage: { en: "Percentage", ar: "نسبة مئوية" },
  in: { en: "In", ar: "وارد" },
  out: { en: "Out", ar: "صادر" },
  output: { en: "Output Tax", ar: "ضريبة مخرجات" },
  input: { en: "Input Tax", ar: "ضريبة مدخلات" },
  exempt: { en: "Exempt", ar: "معفاة" },
  supplier: { en: "Supplier", ar: "مورّد" },
  contractor: { en: "Contractor", ar: "مقاول" },
  planning: { en: "Planning", ar: "تخطيط" },
  completed: { en: "Completed", ar: "مكتمل" },
  on_hold: { en: "On Hold", ar: "معلّق" },
  draft: { en: "Draft", ar: "مسودة" },
  new: { en: "New", ar: "جديد" },
  contacted: { en: "Contacted", ar: "تم التواصل" },
  qualified: { en: "Qualified", ar: "مؤهل" },
  proposal: { en: "Proposal", ar: "عرض" },
  won: { en: "Won", ar: "ناجح" },
  lost: { en: "Lost", ar: "خاسر" },
  monthly: { en: "Monthly", ar: "شهري" },
  quarterly: { en: "Quarterly", ar: "ربع سنوي" },
  semi_annual: { en: "Semi Annual", ar: "نصف سنوي" },
  annual: { en: "Annual", ar: "سنوي" },
  custom: { en: "Custom", ar: "مخصص" },
  note: { en: "Note", ar: "ملاحظة" },
  call: { en: "Call", ar: "اتصال" },
  meeting: { en: "Meeting", ar: "اجتماع" },
  email: { en: "Email", ar: "بريد إلكتروني" },
  visit: { en: "Visit", ar: "زيارة" },
  // accounting: account types
  asset: { en: "Asset", ar: "أصول" },
  liability: { en: "Liability", ar: "التزامات" },
  equity: { en: "Equity", ar: "حقوق ملكية" },
  revenue: { en: "Revenue", ar: "إيرادات" },
  expense: { en: "Expense", ar: "مصروفات" },
  // accounting: normal side
  debit: { en: "Debit", ar: "مدين" },
  credit: { en: "Credit", ar: "دائن" },
  // accounting: journal entry status
  posted: { en: "Posted", ar: "مرحّل" },
  reversed: { en: "Reversed", ar: "معكوس" },
  approved: { en: "Approved", ar: "معتمد" },
  // accounting: cost center kind
  department: { en: "Department", ar: "قسم" },
  project: { en: "Project", ar: "مشروع" },
  branch: { en: "Branch", ar: "فرع" },
  // accounting: profit center kind
  segment: { en: "Segment", ar: "قطاع" },
  // cheques: direction
  incoming: { en: "Incoming", ar: "وارد" },
  outgoing: { en: "Outgoing", ar: "صادر" },
  // cheques: status lifecycle
  post_dated: { en: "Post-dated", ar: "مؤجل الدفع" },
  under_collection: { en: "Under Collection", ar: "قيد التحصيل" },
  deposited: { en: "Deposited", ar: "مودع" },
  cleared: { en: "Cleared", ar: "محصّل" },
  returned: { en: "Returned", ar: "مرتجع" },
  // accounting: fiscal period / budget status
  open: { en: "Open", ar: "مفتوح" },
  // engineering: statuses / types
  in_progress: { en: "In Progress", ar: "قيد التنفيذ" },
  submitted: { en: "Submitted", ar: "مُقدَّم" },
  reviewed: { en: "Reviewed", ar: "مُراجَع" },
  rejected: { en: "Rejected", ar: "مرفوض" },
  superseded: { en: "Superseded", ar: "مُستبدَل" },
  approved_with_comments: { en: "Approved with Comments", ar: "معتمد مع ملاحظات" },
  answered: { en: "Answered", ar: "تمت الإجابة" },
  under_review: { en: "Under Review", ar: "قيد المراجعة" },
  pass: { en: "Pass", ar: "ناجح" },
  fail: { en: "Fail", ar: "راسب" },
  conditional: { en: "Conditional", ar: "مشروط" },
  low: { en: "Low", ar: "منخفض" },
  medium: { en: "Medium", ar: "متوسط" },
  high: { en: "High", ar: "مرتفع" },
  critical: { en: "Critical", ar: "حرج" },
  architectural: { en: "Architectural", ar: "معماري" },
  structural: { en: "Structural", ar: "إنشائي" },
  mep: { en: "MEP", ar: "كهروميكانيكي" },
  rfi: { en: "RFI", ar: "طلب معلومات" },
  technical_submittal: { en: "Technical Submittal", ar: "تقديم فني" },
  material_submittal: { en: "Material Submittal", ar: "تقديم مواد" },
  // construction execution: statuses / types / levels
  verified: { en: "Verified", ar: "مُتحقَّق" },
  suspended: { en: "Suspended", ar: "موقوف" },
  terminated: { en: "Terminated", ar: "منهى" },
  applied: { en: "Applied", ar: "مطبّق" },
  held: { en: "Held", ar: "محتجز" },
  released: { en: "Released", ar: "مُفرَج عنه" },
  partially_released: { en: "Partially Released", ar: "مُفرَج عنه جزئياً" },
  registered: { en: "Registered", ar: "مُسجَّل" },
  recovered: { en: "Recovered", ar: "مُسترَد" },
  addition: { en: "Addition", ar: "إضافة" },
  deduction: { en: "Deduction", ar: "خصم" },
  penalty: { en: "Penalty", ar: "غرامة" },
  delay_penalty: { en: "Delay Penalty", ar: "غرامة تأخير" },
  quality_penalty: { en: "Quality Penalty", ar: "غرامة جودة" },
  other: { en: "Other", ar: "أخرى" },
  extra_work: { en: "Extra Work", ar: "أعمال إضافية" },
  compensation: { en: "Compensation", ar: "تعويض" },
  claim: { en: "Claim", ar: "مطالبة" },
  site_engineer: { en: "Site Engineer", ar: "مهندس موقع" },
  project_manager: { en: "Project Manager", ar: "مدير مشروع" },
  engineering_manager: { en: "Engineering Manager", ar: "مدير هندسي" },
  finance: { en: "Finance", ar: "المالية" },
  // procurement: statuses / classifications / types / levels
  blacklist: { en: "Blacklisted", ar: "قائمة سوداء" },
  local: { en: "Local", ar: "محلي" },
  international: { en: "International", ar: "دولي" },
  manufacturer: { en: "Manufacturer", ar: "مُصنّع" },
  distributor: { en: "Distributor", ar: "موزّع" },
  service_provider: { en: "Service Provider", ar: "مزوّد خدمة" },
  item: { en: "Item", ar: "صنف" },
  service: { en: "Service", ar: "خدمة" },
  urgent: { en: "Urgent", ar: "عاجل" },
  issued: { en: "Issued", ar: "صادر" },
  awarded: { en: "Awarded", ar: "تمت الترسية" },
  invited: { en: "Invited", ar: "مدعو" },
  responded: { en: "Responded", ar: "تم الرد" },
  declined: { en: "Declined", ar: "رفض" },
  received: { en: "Received", ar: "مستلم" },
  under_evaluation: { en: "Under Evaluation", ar: "قيد التقييم" },
  recommended: { en: "Recommended", ar: "موصى به" },
  full: { en: "Full", ar: "كامل" },
  passed: { en: "Passed", ar: "ناجح" },
  failed: { en: "Failed", ar: "فاشل" },
  department_head: { en: "Department Head", ar: "رئيس القسم" },
  procurement_manager: { en: "Procurement Manager", ar: "مدير المشتريات" },
  general_manager: { en: "General Manager", ar: "المدير العام" },
  main: { en: "Main", ar: "رئيسي" },
  transit: { en: "Transit", ar: "عبور" },
  virtual: { en: "Virtual", ar: "افتراضي" },
  quarantine: { en: "Quarantine", ar: "حجر" },
  stock: { en: "Stock", ar: "مخزون" },
  non_stock: { en: "Non-Stock", ar: "غير مخزون" },
  fifo: { en: "FIFO", ar: "الوارد أولاً صادر أولاً" },
  lifo: { en: "LIFO", ar: "الوارد أخيراً صادر أولاً" },
  average: { en: "Average", ar: "المتوسط المرجح" },
  standard: { en: "Standard", ar: "معياري" },
  purchase: { en: "Purchase", ar: "شراء" },
  return: { en: "Return", ar: "مرتجع" },
  transfer: { en: "Transfer", ar: "تحويل" },
  production: { en: "Production", ar: "إنتاج" },
  opening: { en: "Opening", ar: "افتتاحي" },
  consumption: { en: "Consumption", ar: "استهلاك" },
  sale: { en: "Sale", ar: "بيع" },
  disposal: { en: "Disposal", ar: "إتلاف" },
  warehouse: { en: "Warehouse", ar: "مستودع" },
  location: { en: "Location", ar: "موقع" },
  in_transit: { en: "In Transit", ar: "قيد النقل" },
  increase: { en: "Increase", ar: "زيادة" },
  decrease: { en: "Decrease", ar: "نقصان" },
  revaluation: { en: "Revaluation", ar: "إعادة تقييم" },
  damage: { en: "Damage", ar: "تلف" },
  loss: { en: "Loss", ar: "فقدان" },
  expiry: { en: "Expiry", ar: "انتهاء صلاحية" },
  cycle: { en: "Cycle Count", ar: "جرد دوري" },
  spot: { en: "Spot Count", ar: "جرد فوري" },
  receipt: { en: "Receipt", ar: "استلام" },
  issue: { en: "Issue", ar: "صرف" },
  transfer_in: { en: "Transfer In", ar: "تحويل وارد" },
  transfer_out: { en: "Transfer Out", ar: "تحويل صادر" },
  adjustment: { en: "Adjustment", ar: "تسوية" },
  count: { en: "Count", ar: "جرد" },
  // HR: employment types
  full_time: { en: "Full Time", ar: "دوام كامل" },
  part_time: { en: "Part Time", ar: "دوام جزئي" },
  contract: { en: "Contract", ar: "عقد" },
  temporary: { en: "Temporary", ar: "مؤقت" },
  intern: { en: "Intern", ar: "متدرب" },
  // HR: gender / marital status
  male: { en: "Male", ar: "ذكر" },
  female: { en: "Female", ar: "أنثى" },
  single: { en: "Single", ar: "أعزب" },
  married: { en: "Married", ar: "متزوج" },
  divorced: { en: "Divorced", ar: "مطلّق" },
  widowed: { en: "Widowed", ar: "أرمل" },
  // HR: employee / leave statuses
  on_leave: { en: "On Leave", ar: "في إجازة" },
  resigned: { en: "Resigned", ar: "مستقيل" },
  // HR: attendance statuses
  present: { en: "Present", ar: "حاضر" },
  absent: { en: "Absent", ar: "غائب" },
  late: { en: "Late", ar: "متأخر" },
  holiday: { en: "Holiday", ar: "عطلة" },
  weekend: { en: "Weekend", ar: "نهاية الأسبوع" },
  // HR: salary component / payroll
  earning: { en: "Earning", ar: "استحقاق" },
  processing: { en: "Processing", ar: "قيد المعالجة" },
  // HR: loan types / status
  personal: { en: "Personal", ar: "شخصي" },
  housing: { en: "Housing", ar: "سكن" },
  car: { en: "Car", ar: "سيارة" },
  emergency: { en: "Emergency", ar: "طارئ" },
  disbursed: { en: "Disbursed", ar: "مصروف" },
  // HR: evaluation ratings
  excellent: { en: "Excellent", ar: "ممتاز" },
  good: { en: "Good", ar: "جيد" },
  poor: { en: "Poor", ar: "ضعيف" },
  // HR: document types
  id_card: { en: "ID Card", ar: "بطاقة هوية" },
  passport: { en: "Passport", ar: "جواز سفر" },
  visa: { en: "Visa", ar: "تأشيرة" },
  certificate: { en: "Certificate", ar: "شهادة" },
  work_permit: { en: "Work Permit", ar: "تصريح عمل" },
  // Legal: source/contract type, counterparty
  legal: { en: "Legal", ar: "قانوني" },
  sales: { en: "Sales", ar: "مبيعات" },
  construction: { en: "Construction", ar: "إنشاءات" },
  procurement: { en: "Procurement", ar: "مشتريات" },
  employee: { en: "Employee", ar: "موظف" },
  customer: { en: "Customer", ar: "عميل" },
  reservation: { en: "Reservation", ar: "حجز" },
  // Legal: contract lifecycle status
  renewed: { en: "Renewed", ar: "مُجدَّد" },
  // Legal: case type
  civil: { en: "Civil", ar: "مدني" },
  commercial: { en: "Commercial", ar: "تجاري" },
  labor: { en: "Labor", ar: "عمالي" },
  criminal: { en: "Criminal", ar: "جنائي" },
  administrative: { en: "Administrative", ar: "إداري" },
  arbitration: { en: "Arbitration", ar: "تحكيم" },
  // Legal: case role
  plaintiff: { en: "Plaintiff", ar: "مدّعٍ" },
  defendant: { en: "Defendant", ar: "مدّعى عليه" },
  third_party: { en: "Third Party", ar: "طرف ثالث" },
  // Legal: case status
  settled: { en: "Settled", ar: "تمت التسوية" },
  appealed: { en: "Appealed", ar: "مُستأنف" },
  // Legal: hearing status
  scheduled: { en: "Scheduled", ar: "مجدول" },
  adjourned: { en: "Adjourned", ar: "مؤجّل" },
  // Legal: claim type/direction/status
  financial: { en: "Financial", ar: "مالي" },
  contractual: { en: "Contractual", ar: "تعاقدي" },
  damages: { en: "Damages", ar: "تعويضات" },
  by_company: { en: "By Company", ar: "من الشركة" },
  against_company: { en: "Against Company", ar: "ضد الشركة" },
  accepted: { en: "Accepted", ar: "مقبول" },
  // Legal: notice type/status
  warning: { en: "Warning", ar: "إنذار" },
  demand: { en: "Demand", ar: "مطالبة" },
  termination: { en: "Termination", ar: "إنهاء" },
  sent: { en: "Sent", ar: "مُرسل" },
  acknowledged: { en: "Acknowledged", ar: "تم الاستلام" },
  // Legal: advisor type
  internal: { en: "Internal", ar: "داخلي" },
  external: { en: "External", ar: "خارجي" },
  // Unit Handover
  initial: { en: "Initial", ar: "مبدئي" },
  final: { en: "Final", ar: "نهائي" },
  requested: { en: "Requested", ar: "مطلوب" },
  rescheduled: { en: "Rescheduled", ar: "أعيدت جدولته" },
  na: { en: "N/A", ar: "لا ينطبق" },
  resolved: { en: "Resolved", ar: "تم الحل" },
  // Customer Service: channels
  complaint: { en: "Complaint", ar: "شكوى" },
  maintenance: { en: "Maintenance", ar: "صيانة" },
  support: { en: "Support", ar: "دعم" },
  all: { en: "All", ar: "الكل" },
  // Fixed Assets: depreciation methods, statuses, count, disposal types
  straight_line: { en: "Straight Line", ar: "القسط الثابت" },
  declining_balance: { en: "Declining Balance", ar: "القسط المتناقص" },
  under_maintenance: { en: "Under Maintenance", ar: "تحت الصيانة" },
  disposed: { en: "Disposed", ar: "مُستبعد" },
  written_off: { en: "Written Off", ar: "مشطوب" },
  found: { en: "Found", ar: "موجود" },
  missing: { en: "Missing", ar: "مفقود" },
  damaged: { en: "Damaged", ar: "تالف" },
  scrap: { en: "Scrap", ar: "خردة" },
  donation: { en: "Donation", ar: "تبرع" },
  write_off: { en: "Write-off", ar: "شطب" },
};

export function enumLabel(value: string | null | undefined, lang: Lang): string {
  if (!value) return "-";
  const entry = ENUM_LABELS[value];
  return entry ? entry[lang] : value;
}

export interface EnumOption {
  value: string;
  label: string;
  labelAr: string;
}

export function enumOptions(values: string[]): EnumOption[] {
  return values.map((v) => {
    const e = ENUM_LABELS[v];
    return { value: v, label: e?.en ?? v, labelAr: e?.ar ?? v };
  });
}
