import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "ar";

type LanguageProviderProps = {
  children: React.ReactNode;
  defaultLanguage?: Language;
  storageKey?: string;
};

type LanguageProviderState = {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
};

const initialState: LanguageProviderState = {
  language: "en",
  setLanguage: () => null,
  dir: "ltr",
  t: (key) => key,
};

const LanguageProviderContext = createContext<LanguageProviderState>(initialState);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "login.title": "Sign In",
    "login.subtitle": "Enter your credentials to access the ERP.",
    "login.username": "Username",
    "login.password": "Password",
    "login.submit": "Sign In",
    "login.defaultCredentials": "Default super administrator credentials",
    "nav.dashboard": "Dashboard",
    "nav.users": "Users",
    "nav.roles": "Roles",
    "nav.companies": "Companies",
    "nav.branches": "Branches",
    "nav.fiscal_years": "Fiscal Years",
    "nav.currencies": "Currencies",
    "nav.number_sequences": "Number Sequences",
    "nav.audit_logs": "Audit Logs",
    "nav.login_history": "Login History",
    "nav.settings": "Settings",
    "nav.change_password": "Change Password",
    "nav.logout": "Logout",
    "nav.group.general": "General",
    "nav.group.real_estate": "Real Estate",
    "nav.group.unit_management": "Unit Management",
    "nav.group.crm": "CRM",
    "nav.group.customers": "Customers",
    "nav.group.sales": "Sales",
    "nav.group.installments": "Installments",
    "nav.group.finance": "Finance & Collections",
    "nav.group.administration": "Administration",
    "nav.projects": "Projects",
    "nav.phases": "Phases",
    "nav.buildings": "Buildings",
    "nav.floors": "Floors",
    "nav.units": "Units",
    "nav.unit_types": "Unit Types",
    "nav.unit_statuses": "Unit Statuses",
    "nav.unit_price_lists": "Price Lists",
    "nav.unit_pricing": "Unit Pricing",
    "nav.unit_discounts": "Discounts",
    "nav.leads": "Leads",
    "nav.lead_sources": "Lead Sources",
    "nav.lead_activities": "Lead Activities",
    "nav.lead_follow_ups": "Follow-ups",
    "nav.lead_assignments": "Assignments",
    "nav.lead_conversions": "Conversions",
    "nav.customers": "Customers",
    "nav.customer_contacts": "Contacts",
    "nav.customer_documents": "Documents",
    "nav.customer_notes": "Notes",
    "nav.reservations": "Reservations",
    "nav.reservation_payments": "Reservation Payments",
    "nav.reservation_notes": "Reservation Notes",
    "nav.reservation_documents": "Reservation Documents",
    "nav.contracts": "Contracts",
    "nav.contract_amendments": "Amendments",
    "nav.contract_cancellations": "Cancellations",
    "nav.contract_notes": "Contract Notes",
    "nav.contract_documents": "Contract Documents",
    "nav.unit_transfers": "Unit Transfers",
    "nav.installment_plans": "Installment Plans",
    "nav.installment_schedules": "Schedules",
    "nav.installment_collections": "Collections",
    "nav.penalty_rules": "Penalty Rules",
    "nav.cashboxes": "Cashboxes",
    "nav.treasury_transactions": "Treasury Transactions",
    "nav.bank_accounts": "Bank Accounts",
    "nav.bank_transactions": "Bank Transactions",
    "nav.receipts": "Receipts",
    "nav.penalties": "Penalties",
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome",
    "dashboard.users": "Users",
    "dashboard.companies": "Companies",
    "dashboard.branches": "Branches",
    "dashboard.roles": "Roles",
    "dashboard.active_sessions": "Active Sessions",
    "dashboard.fiscal_years": "Fiscal Years",
    "dashboard.currencies": "Currencies",
    "dashboard.audit_events": "Audit Events",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.real_estate": "Real Estate Overview",
    "dashboard.projects": "Projects",
    "dashboard.buildings": "Buildings",
    "dashboard.units": "Units",
    "dashboard.available_units": "Available Units",
    "dashboard.reserved_units": "Reserved Units",
    "dashboard.sold_units": "Sold Units",
    "dashboard.leads": "Leads",
    "dashboard.customers": "Customers",
    "dashboard.reservations": "Reservations",
    "dashboard.contracts": "Contracts",
    "dashboard.overdue_installments": "Overdue Installments",
    "dashboard.total_contract_value": "Total Contract Value",
    "dashboard.finance": "Finance & Collections",
    "dashboard.total_sales": "Total Sales",
    "dashboard.total_collections": "Total Collections",
    "dashboard.outstanding_installments": "Outstanding Installments",
    "dashboard.overdue_amount": "Overdue Amount",
    "dashboard.treasury_balance": "Treasury Balance",
    "dashboard.bank_balance": "Bank Balance",
    "dashboard.receipts": "Receipts",
    "dashboard.pending_penalties": "Pending Penalties",
    "common.actions": "Actions",
    "common.create": "Create",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.search": "Search...",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.locked": "Locked",
    "common.open": "Open",
    "common.closed": "Closed",
    "common.loading": "Loading...",
    "common.count": "Count",
    "common.export": "Export",
    "common.export_excel": "Export to Excel",
    "common.export_pdf": "Export to PDF",
    "common.no_results": "No records found",
    "common.total": "Total",
    "common.created": "Created successfully",
    "common.saved": "Saved successfully",
    "common.deleted": "Deleted successfully",
    "common.updated": "Updated successfully",
    "common.error": "Something went wrong",
    "users.title": "Users",
    "users.create": "Create User",
    "users.edit": "Edit User",
    "users.delete_confirm": "Are you sure you want to delete this user?",
    "roles.title": "Roles",
    "roles.create": "Create Role",
    "companies.title": "Companies",
    "companies.create": "Create Company",
    "branches.title": "Branches",
    "branches.create": "Create Branch",
    "fiscal_years.title": "Fiscal Years",
    "fiscal_years.create": "Create Fiscal Year",
    "currencies.title": "Currencies",
    "currencies.create": "Create Currency",
    "number_sequences.title": "Number Sequences",
    "number_sequences.create": "Create Number Sequence",
    "audit_logs.title": "Audit Logs",
    "login_history.title": "Login History",
    "settings.title": "Settings",
    "change_password.title": "Change Password",
    "change_password.current": "Current Password",
    "change_password.new": "New Password",
    "change_password.confirm": "Confirm New Password",
    "change_password.submit": "Change Password",
    "change_password.success": "Password changed successfully",
    "change_password.error": "Failed to change password",
    "common.update": "Update",
    "common.delete_confirm": "Are you sure you want to delete this record?",
    "common.code": "Code",
    "common.name": "Name",
    "common.name_ar": "Name (Arabic)",
    "common.email": "Email",
    "common.username": "Username",
    "common.password": "Password",
    "common.company": "Company",
    "common.manager": "Manager",
    "common.description": "Description",
    "common.type": "Type",
    "common.symbol": "Symbol",
    "common.start_date": "Start Date",
    "common.end_date": "End Date",
    "common.user": "User",
    "common.timestamp": "Timestamp",
    "common.action": "Action",
    "common.entity": "Entity",
    "common.details": "Details",
    "common.success": "Success",
    "common.failed": "Failed",
    "roles.system": "System",
    "roles.users": "Users",
    "roles.permissions": "Permissions",
    "branches.filter_company": "Filter by company",
    "branches.select_company": "Select a company",
    "currencies.base": "Base",
    "currencies.code_hint": "Code (e.g. SAR)",
    "number_sequences.prefix": "Prefix",
    "number_sequences.next": "Next",
    "number_sequences.sample": "Sample",
    "number_sequences.padding": "Padding",
    "audit_logs.filter_entity": "Filter by entity (e.g. users)",
    "audit_logs.filter_action": "Filter by action (e.g. update)",
    "login_history.ip": "IP Address",
    "login_history.user_agent": "User Agent",
    "settings.saved": "Settings saved successfully",
    "settings.save_failed": "Failed to save settings",
    "change_password.mismatch": "New passwords do not match",
    "change_password.req_length": "Password must be at least 8 characters long",
    "change_password.req_upper": "Password must contain at least one uppercase letter",
    "change_password.req_lower": "Password must contain at least one lowercase letter",
    "change_password.req_number": "Password must contain at least one number",
    "change_password.hint": "Min 8 chars, 1 uppercase, 1 lowercase, 1 number",
    "common.name_en": "Name (English)",
    "common.full_name": "Full Name",
    "branches.all_companies": "All Companies",
    "fiscal_years.name_hint": "Name (e.g. 2026)",
    "number_sequences.document_type": "Document Type",
    "number_sequences.prefix_hint": "Prefix (e.g. INV-)",
    "number_sequences.next_number": "Next Number",
    "number_sequences.reset_yearly": "Reset counter yearly",
    "not_found.title": "Page Not Found",
    "not_found.message": "The page you are looking for does not exist.",
    "nav.group.accounting": "Accounting",
    "nav.accounting_dashboard": "Financial Dashboard",
    "nav.accounts": "Chart of Accounts",
    "nav.cost_centers": "Cost Centers",
    "nav.journal_entries": "Journal Entries",
    "nav.general_ledger": "General Ledger",
    "nav.trial_balance": "Trial Balance",
    "nav.balance_sheet": "Balance Sheet",
    "nav.income_statement": "Income Statement",
    "nav.cash_flow": "Cash Flow",
    "nav.fiscal_periods": "Fiscal Periods",
    "nav.budgets": "Budgets",
    "nav.budget_lines": "Budget Lines",
    "nav.budget_vs_actual": "Budget vs Actual",
    "nav.account_mappings": "Account Mappings",
    "nav.group.financial_management": "Financial Management & Accounting",
    "nav.group.collections_installments": "Collections & Installments",
    "nav.cheques": "Cheque Management",
    "nav.cheque_status_history": "Cheque Status History",
    "nav.cheque_reports": "Cheque Reports",
    "acc.cheque_reports_desc": "Filter cheques by direction and status: post-dated, under collection, deposited, cleared, returned, cancelled.",
    "acc.count": "Count",
    "acc.total_amount": "Total Amount",
    "common.all": "All",
    "nav.profit_centers": "Profit Centers",
    "nav.year_end_closing": "Year-End Closing",
    "nav.financial_reports": "Financial Reports",
    "nav.group.engineering": "Engineering",
    "nav.engineering_dashboard": "Engineering Dashboard",
    "nav.engineering_disciplines": "Disciplines",
    "nav.consultants": "Consultants",
    "nav.design_packages": "Design Packages",
    "nav.drawing_categories": "Drawing Categories",
    "nav.technical_specifications": "Technical Specifications",
    "nav.drawings": "Drawings",
    "nav.drawing_revisions": "Drawing Revisions",
    "nav.boqs": "Bills of Quantities",
    "nav.boq_items": "BOQ Items",
    "nav.boq_quantity_revisions": "BOQ Quantity Revisions",
    "nav.cost_estimates": "Cost Estimates",
    "nav.inspection_requests": "Inspection Requests",
    "nav.inspection_reports": "Inspection Reports",
    "nav.defects": "Defects",
    "nav.corrective_actions": "Corrective Actions",
    "nav.rfis": "RFIs",
    "nav.technical_submittals": "Technical Submittals",
    "nav.material_submittals": "Material Submittals",
    "nav.consultant_responses": "Consultant Responses",
    "nav.engineering_progress": "Engineering Progress",
    "eng.drawings_count": "Total Drawings",
    "eng.pending_drawing_approvals": "Pending Drawing Approvals",
    "eng.boq_count": "Bills of Quantities",
    "eng.total_boq_value": "Total BOQ Value",
    "eng.open_rfis": "Open RFIs",
    "eng.open_defects": "Open Defects",
    "eng.open_inspections": "Open Inspections",
    "eng.consultants_count": "Consultants",
    "eng.drawings_by_status": "Drawings by Approval Status",
    "eng.defects_by_severity": "Defects by Severity",
    "eng.no_data": "No data available",
    "nav.group.construction": "Construction Execution",
    "nav.construction_dashboard": "Construction Dashboard",
    "nav.contractors": "Contractors",
    "nav.contractor_contracts": "Contractor Contracts",
    "nav.contract_boq_items": "Contract BOQ Items",
    "nav.work_progress_updates": "Work Progress Updates",
    "nav.payment_certificates": "Contractor Payment Certificates",
    "nav.certificate_items": "Certificate Line Items",
    "nav.certificate_statuses": "Certificate Statuses",
    "nav.certificate_approvals": "Certificate Approvals",
    "nav.certificate_approval_logs": "Certificate Approval Log",
    "nav.variation_orders": "Variation Orders",
    "nav.contractor_deductions": "Contractor Deductions",
    "nav.contractor_additions": "Contractor Additions",
    "nav.retentions": "Retentions",
    "nav.advance_payments": "Advance Payments",
    "nav.advance_recoveries": "Advance Recoveries",
    "nav.contractor_invoices": "Contractor Invoices",
    "nav.contract_approvals": "Contract Approvals",
    "nav.construction_reports": "Construction Reports",
    "con.contracts_count": "Total Contracts",
    "con.active_contracts": "Active Contracts",
    "con.total_contract_value": "Total Contract Value",
    "con.total_certified": "Total Certified",
    "con.total_deductions": "Total Deductions",
    "con.total_additions": "Total Additions",
    "con.retention_held": "Retention Held",
    "con.open_variations": "Open Variations",
    "con.pending_approvals": "Pending Approvals",
    "con.pending_invoices": "Pending Invoices",
    "con.contracts_by_status": "Contracts by Status",
    "con.certificates_by_status": "Certificates by Status",
    "con.no_data": "No data available",
    "con.reports": "Construction Reports",
    "con.reports_subtitle": "Financial summaries across contractors and contracts",
    "con.report_contract_financials": "Contract Financial Summary",
    "con.report_certificates": "Certificate Register",
    "con.report_retention": "Retention Summary",
    "con.report_advances": "Advance Payments Summary",
    "con.report_certificate_register": "Certificate Register",
    "con.report_outstanding_certificates": "Outstanding Certificates",
    "con.report_certificate_retention": "Certificate Retention Report",
    "con.report_advance_recovery": "Advance Recovery Report",
    "con.contract": "Contract",
    "con.contractor": "Contractor",
    "con.certified": "Certified",
    "con.net": "Net",
    "con.gross": "Gross",
    "con.retained": "Retained",
    "con.released": "Released",
    "con.recovered": "Recovered",
    "con.count": "Count",
    "con.total": "Total",
    "con.date": "Date",
    "con.amount": "Amount",
    "con.outstanding": "Outstanding",
    "nav.group.procurement": "Procurement",
    "nav.procurement_dashboard": "Procurement Dashboard",
    "nav.supplier_categories": "Supplier Categories",
    "nav.suppliers": "Suppliers",
    "nav.supplier_contacts": "Supplier Contacts",
    "nav.supplier_evaluations": "Supplier Evaluations",
    "nav.purchase_requests": "Purchase Requests",
    "nav.purchase_request_items": "Purchase Request Items",
    "nav.rfqs": "Requests for Quotation",
    "nav.rfq_items": "RFQ Items",
    "nav.rfq_suppliers": "RFQ Suppliers",
    "nav.supplier_quotations": "Supplier Quotations",
    "nav.quotation_items": "Quotation Items",
    "nav.purchase_orders": "Purchase Orders",
    "nav.purchase_order_items": "Purchase Order Items",
    "nav.purchase_contracts": "Purchase Contracts",
    "nav.purchase_contract_amendments": "Purchase Contract Amendments",
    "nav.goods_receipt_notes": "Goods Receipt Notes",
    "nav.grn_items": "GRN Items",
    "nav.purchase_returns": "Purchase Returns",
    "nav.purchase_return_items": "Purchase Return Items",
    "nav.procurement_approvals": "Procurement Approvals",
    "nav.procurement_reports": "Procurement Reports",
    "nav.group.inventory": "Inventory",
    "nav.inventory_dashboard": "Inventory Dashboard",
    "nav.warehouses": "Warehouses",
    "nav.warehouse_locations": "Warehouse Locations",
    "nav.item_categories": "Item Categories",
    "nav.item_groups": "Item Groups",
    "nav.units_of_measure": "Units of Measure",
    "nav.inventory_items": "Inventory Items",
    "nav.reorder_levels": "Reorder Levels",
    "nav.stock_opening_balances": "Stock Opening Balances",
    "nav.goods_receipts": "Goods Receipts",
    "nav.goods_receipt_items": "Goods Receipt Items",
    "nav.goods_issues": "Goods Issues",
    "nav.goods_issue_items": "Goods Issue Items",
    "nav.inventory_transfers": "Inventory Transfers",
    "nav.inventory_transfer_items": "Inventory Transfer Items",
    "nav.stock_adjustments": "Stock Adjustments",
    "nav.stock_adjustment_items": "Stock Adjustment Items",
    "nav.stock_counts": "Stock Counts",
    "nav.stock_count_items": "Stock Count Items",
    "nav.inventory_ledger": "Inventory Ledger",
    "nav.inventory_reports": "Inventory Reports",
    "inv.items_count": "Total Items",
    "inv.active_items": "Active Items",
    "inv.warehouses_count": "Warehouses",
    "inv.low_stock_items": "Low Stock Items",
    "inv.total_stock_value": "Total Stock Value",
    "inv.pending_receipts": "Pending Receipts",
    "inv.pending_issues": "Pending Issues",
    "inv.pending_transfers": "Pending Transfers",
    "inv.pending_adjustments": "Pending Adjustments",
    "inv.receipts_by_status": "Goods Receipts by Status",
    "inv.issues_by_status": "Goods Issues by Status",
    "inv.no_data": "No data available",
    "inv.reports": "Inventory Reports",
    "inv.reports_subtitle": "Stock movements and valuation summaries",
    "inv.report_receipts": "Goods Receipts Summary",
    "inv.report_issues": "Goods Issues Summary",
    "inv.report_adjustments": "Stock Adjustments Summary",
    "inv.report_opening": "Opening Balances Summary",
    "inv.count": "Count",
    "inv.total": "Total",
    "proc.suppliers_count": "Total Suppliers",
    "proc.active_suppliers": "Active Suppliers",
    "proc.open_rfqs": "Open RFQs",
    "proc.pending_requests": "Pending Requests",
    "proc.open_purchase_orders": "Open Purchase Orders",
    "proc.purchase_volume": "Purchase Volume",
    "proc.total_contract_value": "Total Contract Value",
    "proc.pending_approvals": "Pending Approvals",
    "proc.pending_returns": "Pending Returns",
    "proc.purchase_orders_by_status": "Purchase Orders by Status",
    "proc.requests_by_status": "Requests by Status",
    "proc.no_data": "No data available",
    "proc.reports": "Procurement Reports",
    "proc.reports_subtitle": "Financial summaries across suppliers and purchases",
    "proc.report_supplier_volume": "Supplier Purchase Volume",
    "proc.report_orders": "Purchase Orders Summary",
    "proc.report_receipts": "Goods Receipt Summary",
    "proc.report_returns": "Purchase Returns Summary",
    "proc.supplier": "Supplier",
    "proc.count": "Count",
    "proc.total": "Total",
    "acc.account": "Account",
    "acc.parent": "Parent Account",
    "acc.parent_cost_center": "Parent Cost Center",
    "acc.type": "Type",
    "acc.normal_side": "Normal Side",
    "acc.postable": "Postable",
    "acc.kind": "Kind",
    "acc.period": "Period",
    "acc.period_number": "Period Number",
    "acc.start_date": "Start Date",
    "acc.end_date": "End Date",
    "acc.entry_date": "Entry Date",
    "acc.reference": "Reference",
    "acc.description": "Description",
    "acc.direction": "Direction",
    "acc.cheque_number": "Cheque Number",
    "acc.cheque_date": "Cheque Date",
    "acc.due_date": "Due Date",
    "acc.bank_name": "Bank Name",
    "acc.payee_name": "Payee Name",
    "acc.change_status": "Change Status",
    "acc.return_reason": "Return Reason",
    "acc.action_date": "Action Date",
    "acc.related_unit": "Related Unit",
    "acc.related_installment": "Related Installment",
    "acc.collection_date": "Collection Date",
    "acc.attachments": "Attachments",
    "acc.from_status": "From Status",
    "acc.to_status": "To Status",
    "acc.actor": "Actor",
    "acc.action": "Action",
    "acc.cheques_pending": "Pending Cheques",
    "acc.cheques_cleared": "Cleared Cheques",
    "acc.cheques_due": "Cheques Due (Amount)",
    "acc.close_year": "Close Year",
    "acc.reopen_year": "Reopen Year",
    "acc.closing_date": "Closing Date",
    "acc.reports_hub_subtitle": "Generate and export financial statements",
    "acc.open_report": "Open Report",
    "acc.debit": "Debit",
    "acc.credit": "Credit",
    "acc.total_debit": "Total Debit",
    "acc.total_credit": "Total Credit",
    "acc.balance": "Balance",
    "acc.opening_balance": "Opening Balance",
    "acc.closing_balance": "Closing Balance",
    "acc.lines": "Lines",
    "acc.add_line": "Add Line",
    "acc.balanced": "Balanced",
    "acc.not_balanced": "Not balanced",
    "export.excel": "Export to Excel",
    "export.pdf": "Export to PDF",
    "export.generated": "Generated",
    "export.period": "Period",
    "export.from": "From",
    "export.to": "To",
    "export.as_of": "As of",
    "acc.post": "Post",
    "acc.reverse": "Reverse",
    "acc.approve": "Approve",
    "acc.close": "Close",
    "acc.reopen": "Reopen",
    "acc.new_entry": "New Journal Entry",
    "acc.event_key": "Event Key",
    "acc.debit_account": "Debit Account",
    "acc.credit_account": "Credit Account",
    "acc.budget": "Budget",
    "acc.fiscal_year": "Fiscal Year",
    "acc.amount": "Amount",
    "acc.from_date": "From Date",
    "acc.to_date": "To Date",
    "acc.as_of_date": "As of Date",
    "acc.run_report": "Run Report",
    "acc.assets": "Assets",
    "acc.liabilities": "Liabilities",
    "acc.equity": "Equity",
    "acc.total_assets": "Total Assets",
    "acc.total_liabilities": "Total Liabilities",
    "acc.total_equity": "Total Equity",
    "acc.revenue": "Revenue",
    "acc.expenses": "Expenses",
    "acc.total_revenue": "Total Revenue",
    "acc.total_expenses": "Total Expenses",
    "acc.net_income": "Net Income",
    "acc.operating": "Operating",
    "acc.investing": "Investing",
    "acc.financing": "Financing",
    "acc.net_change": "Net Change",
    "acc.opening_cash": "Opening Cash",
    "acc.closing_cash": "Closing Cash",
    "acc.budgeted": "Budgeted",
    "acc.actual": "Actual",
    "acc.variance": "Variance",
    "acc.select_account": "Select an account",
    "acc.select_budget": "Select a budget",
    "acc.no_data": "No data for the selected criteria",
    "acc.recent_entries": "Recent Journal Entries",
    "acc.draft_entries": "Draft Entries",
    "acc.posted_entries": "Posted Entries",
    "acc.open_periods": "Open Periods",
    "acc.entry_count": "Total Entries",
    "acc.select_account_prompt": "Select an account to view its ledger.",
    "acc.automatic": "Auto",
    "acc.export": "Export",
    "acc.export_excel": "Export to Excel",
    "acc.export_pdf": "Export to PDF",
    "acc.generated": "Generated",
    "acc.all_dates": "All dates",
    "acc.cancel": "Cancel",
    "nav.group.invoicing": "Invoicing & Receivables",
    "nav.tax_codes": "Tax Codes",
    "nav.customer_invoices": "Customer Invoices",
    "nav.supplier_invoices": "Supplier Invoices",
    "nav.payment_vouchers": "Payment Vouchers",
    "nav.ar_aging": "AR Aging",
    "nav.ap_aging": "AP Aging",
    "nav.tax_report": "Tax Report",
    "tax.name": "Name",
    "tax.name_ar": "Name (Arabic)",
    "tax.type": "Type",
    "tax.rate": "Rate (%)",
    "tax.account": "Tax Account",
    "tax.code": "Tax Code",
    "tax.base": "Base Amount",
    "tax.tax": "Tax Amount",
    "tax.output_tax": "Output Tax",
    "tax.input_tax": "Input Tax",
    "tax.net_tax": "Net Tax",
    "aging.party": "Party",
    "aging.current": "Current",
    "aging.days30": "1-30 Days",
    "aging.days60": "31-60 Days",
    "aging.days90": "61-90 Days",
    "aging.days120": "91+ Days",
    "inv.customer": "Customer",
    "inv.supplier": "Supplier",
    "inv.contract": "Contract",
    "inv.invoice_date": "Invoice Date",
    "inv.supplier_invoice_number": "Supplier Invoice No.",
    "inv.lines": "Lines",
    "inv.line_description": "Description",
    "inv.qty": "Qty",
    "inv.unit_price": "Unit Price",
    "inv.revenue_account": "Revenue Account",
    "inv.expense_account": "Expense Account",
    "inv.line_total": "Line Total",
    "inv.add_line": "Add Line",
    "inv.subtotal": "Subtotal",
    "inv.tax_total": "Tax",
    "inv.paid": "Paid",
    "inv.new_customer_invoice": "New Customer Invoice",
    "inv.new_supplier_invoice": "New Supplier Invoice",
    "inv.no_lines": "Add at least one line",
    "pv.new_voucher": "New Payment Voucher",
    "pv.payee_type": "Payee Type",
    "pv.contractor": "Contractor",
    "pv.payee": "Payee",
    "pv.payment_date": "Payment Date",
    "pv.payment_method": "Payment Method",
    "pv.allocations": "Invoice Allocations",
    "pv.add_allocation": "Add Allocation",
  },
  ar: {
    "login.title": "تسجيل الدخول",
    "login.subtitle": "أدخل بيانات الاعتماد الخاصة بك للوصول.",
    "login.username": "اسم المستخدم",
    "login.password": "كلمة المرور",
    "login.submit": "تسجيل الدخول",
    "login.defaultCredentials": "بيانات اعتماد المسؤول الأعلى الافتراضية",
    "nav.dashboard": "لوحة القيادة",
    "nav.users": "المستخدمين",
    "nav.roles": "الأدوار",
    "nav.companies": "الشركات",
    "nav.branches": "الفروع",
    "nav.fiscal_years": "السنوات المالية",
    "nav.currencies": "العملات",
    "nav.number_sequences": "التسلسلات الرقمية",
    "nav.audit_logs": "سجلات التدقيق",
    "nav.login_history": "سجل تسجيل الدخول",
    "nav.settings": "الإعدادات",
    "nav.change_password": "تغيير كلمة المرور",
    "nav.logout": "تسجيل الخروج",
    "nav.group.general": "عام",
    "nav.group.real_estate": "العقارات",
    "nav.group.unit_management": "إدارة الوحدات",
    "nav.group.crm": "إدارة العلاقات",
    "nav.group.customers": "العملاء",
    "nav.group.sales": "المبيعات",
    "nav.group.installments": "الأقساط",
    "nav.group.finance": "المالية والتحصيلات",
    "nav.group.administration": "الإدارة",
    "nav.projects": "المشاريع",
    "nav.phases": "المراحل",
    "nav.buildings": "المباني",
    "nav.floors": "الطوابق",
    "nav.units": "الوحدات",
    "nav.unit_types": "أنواع الوحدات",
    "nav.unit_statuses": "حالات الوحدات",
    "nav.unit_price_lists": "قوائم الأسعار",
    "nav.unit_pricing": "تسعير الوحدات",
    "nav.unit_discounts": "الخصومات",
    "nav.leads": "العملاء المحتملون",
    "nav.lead_sources": "مصادر العملاء",
    "nav.lead_activities": "الأنشطة",
    "nav.lead_follow_ups": "المتابعات",
    "nav.lead_assignments": "التعيينات",
    "nav.lead_conversions": "التحويلات",
    "nav.customers": "العملاء",
    "nav.customer_contacts": "جهات الاتصال",
    "nav.customer_documents": "المستندات",
    "nav.customer_notes": "الملاحظات",
    "nav.reservations": "الحجوزات",
    "nav.reservation_payments": "مدفوعات الحجز",
    "nav.reservation_notes": "ملاحظات الحجوزات",
    "nav.reservation_documents": "مستندات الحجوزات",
    "nav.contracts": "العقود",
    "nav.contract_amendments": "تعديلات العقود",
    "nav.contract_cancellations": "إلغاءات العقود",
    "nav.contract_notes": "ملاحظات العقود",
    "nav.contract_documents": "مستندات العقود",
    "nav.unit_transfers": "نقل الوحدات",
    "nav.installment_plans": "خطط الأقساط",
    "nav.installment_schedules": "جداول الأقساط",
    "nav.installment_collections": "التحصيلات",
    "nav.penalty_rules": "قواعد الغرامات",
    "nav.cashboxes": "الخزائن",
    "nav.treasury_transactions": "حركات الخزينة",
    "nav.bank_accounts": "الحسابات البنكية",
    "nav.bank_transactions": "الحركات البنكية",
    "nav.receipts": "سندات القبض",
    "nav.penalties": "الغرامات",
    "dashboard.title": "لوحة القيادة",
    "dashboard.welcome": "مرحباً",
    "dashboard.users": "المستخدمين",
    "dashboard.companies": "الشركات",
    "dashboard.branches": "الفروع",
    "dashboard.roles": "الأدوار",
    "dashboard.active_sessions": "الجلسات النشطة",
    "dashboard.fiscal_years": "السنوات المالية",
    "dashboard.currencies": "العملات",
    "dashboard.audit_events": "أحداث التدقيق",
    "dashboard.recent_activity": "النشاط الأخير",
    "dashboard.real_estate": "نظرة عامة على العقارات",
    "dashboard.projects": "المشاريع",
    "dashboard.buildings": "المباني",
    "dashboard.units": "الوحدات",
    "dashboard.available_units": "الوحدات المتاحة",
    "dashboard.reserved_units": "الوحدات المحجوزة",
    "dashboard.sold_units": "الوحدات المباعة",
    "dashboard.leads": "العملاء المحتملون",
    "dashboard.customers": "العملاء",
    "dashboard.reservations": "الحجوزات",
    "dashboard.contracts": "العقود",
    "dashboard.overdue_installments": "الأقساط المتأخرة",
    "dashboard.total_contract_value": "إجمالي قيمة العقود",
    "dashboard.finance": "المالية والتحصيلات",
    "dashboard.total_sales": "إجمالي المبيعات",
    "dashboard.total_collections": "إجمالي التحصيلات",
    "dashboard.outstanding_installments": "الأقساط المستحقة",
    "dashboard.overdue_amount": "المبلغ المتأخر",
    "dashboard.treasury_balance": "رصيد الخزينة",
    "dashboard.bank_balance": "الرصيد البنكي",
    "dashboard.receipts": "سندات القبض",
    "dashboard.pending_penalties": "غرامات معلقة",
    "common.actions": "الإجراءات",
    "common.create": "إنشاء",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.search": "بحث...",
    "common.status": "الحالة",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.locked": "مغلق",
    "common.open": "مفتوح",
    "common.closed": "مغلق",
    "common.loading": "جار التحميل...",
    "common.count": "العدد",
    "common.export": "تصدير",
    "common.export_excel": "تصدير إلى Excel",
    "common.export_pdf": "تصدير إلى PDF",
    "common.no_results": "لا توجد سجلات",
    "common.total": "الإجمالي",
    "common.created": "تم الإنشاء بنجاح",
    "common.saved": "تم الحفظ بنجاح",
    "common.deleted": "تم الحذف بنجاح",
    "common.updated": "تم التحديث بنجاح",
    "common.error": "حدث خطأ ما",
    "users.title": "المستخدمين",
    "users.create": "إنشاء مستخدم",
    "users.edit": "تعديل مستخدم",
    "users.delete_confirm": "هل أنت متأكد أنك تريد حذف هذا المستخدم؟",
    "roles.title": "الأدوار",
    "roles.create": "إنشاء دور",
    "companies.title": "الشركات",
    "companies.create": "إنشاء شركة",
    "branches.title": "الفروع",
    "branches.create": "إنشاء فرع",
    "fiscal_years.title": "السنوات المالية",
    "fiscal_years.create": "إنشاء سنة مالية",
    "currencies.title": "العملات",
    "currencies.create": "إنشاء عملة",
    "number_sequences.title": "التسلسلات الرقمية",
    "number_sequences.create": "إنشاء تسلسل رقمي",
    "audit_logs.title": "سجلات التدقيق",
    "login_history.title": "سجل تسجيل الدخول",
    "settings.title": "الإعدادات",
    "change_password.title": "تغيير كلمة المرور",
    "change_password.current": "كلمة المرور الحالية",
    "change_password.new": "كلمة المرور الجديدة",
    "change_password.confirm": "تأكيد كلمة المرور الجديدة",
    "change_password.submit": "تغيير كلمة المرور",
    "change_password.success": "تم تغيير كلمة المرور بنجاح",
    "change_password.error": "فشل في تغيير كلمة المرور",
    "common.update": "تحديث",
    "common.delete_confirm": "هل أنت متأكد من حذف هذا السجل؟",
    "common.code": "الكود",
    "common.name": "الاسم",
    "common.name_ar": "الاسم (عربي)",
    "common.email": "البريد الإلكتروني",
    "common.username": "اسم المستخدم",
    "common.password": "كلمة المرور",
    "common.company": "الشركة",
    "common.manager": "المدير",
    "common.description": "الوصف",
    "common.type": "النوع",
    "common.symbol": "الرمز",
    "common.start_date": "تاريخ البداية",
    "common.end_date": "تاريخ النهاية",
    "common.user": "المستخدم",
    "common.timestamp": "الطابع الزمني",
    "common.action": "الإجراء",
    "common.entity": "الكيان",
    "common.details": "التفاصيل",
    "common.success": "نجاح",
    "common.failed": "فشل",
    "roles.system": "نظام",
    "roles.users": "المستخدمون",
    "roles.permissions": "الصلاحيات",
    "branches.filter_company": "تصفية حسب الشركة",
    "branches.select_company": "اختر شركة",
    "currencies.base": "أساسية",
    "currencies.code_hint": "الرمز (مثل SAR)",
    "number_sequences.prefix": "البادئة",
    "number_sequences.next": "التالي",
    "number_sequences.sample": "نموذج",
    "number_sequences.padding": "عدد الخانات",
    "audit_logs.filter_entity": "تصفية حسب الكيان (مثل users)",
    "audit_logs.filter_action": "تصفية حسب الإجراء (مثل update)",
    "login_history.ip": "عنوان IP",
    "login_history.user_agent": "وكيل المستخدم",
    "settings.saved": "تم حفظ الإعدادات بنجاح",
    "settings.save_failed": "فشل حفظ الإعدادات",
    "change_password.mismatch": "كلمتا المرور غير متطابقتين",
    "change_password.req_length": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
    "change_password.req_upper": "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
    "change_password.req_lower": "يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل",
    "change_password.req_number": "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
    "change_password.hint": "8 أحرف على الأقل، حرف كبير، حرف صغير، ورقم",
    "common.name_en": "الاسم (إنجليزي)",
    "common.full_name": "الاسم الكامل",
    "branches.all_companies": "كل الشركات",
    "fiscal_years.name_hint": "الاسم (مثل 2026)",
    "number_sequences.document_type": "نوع المستند",
    "number_sequences.prefix_hint": "البادئة (مثل INV-)",
    "number_sequences.next_number": "الرقم التالي",
    "number_sequences.reset_yearly": "إعادة تعيين العداد سنوياً",
    "not_found.title": "الصفحة غير موجودة",
    "not_found.message": "الصفحة التي تبحث عنها غير موجودة.",
    "nav.group.accounting": "المحاسبة",
    "nav.accounting_dashboard": "لوحة المعلومات المالية",
    "nav.accounts": "دليل الحسابات",
    "nav.cost_centers": "مراكز التكلفة",
    "nav.journal_entries": "القيود اليومية",
    "nav.general_ledger": "دفتر الأستاذ العام",
    "nav.trial_balance": "ميزان المراجعة",
    "nav.balance_sheet": "الميزانية العمومية",
    "nav.income_statement": "قائمة الدخل",
    "nav.cash_flow": "التدفقات النقدية",
    "nav.fiscal_periods": "الفترات المالية",
    "nav.budgets": "الموازنات",
    "nav.budget_lines": "بنود الموازنة",
    "nav.budget_vs_actual": "الموازنة مقابل الفعلي",
    "nav.account_mappings": "ربط الحسابات",
    "nav.group.financial_management": "الإدارة المالية والمحاسبة",
    "nav.group.collections_installments": "التحصيلات والأقساط",
    "nav.cheques": "إدارة الشيكات",
    "nav.cheque_status_history": "سجل حالات الشيكات",
    "nav.cheque_reports": "تقارير الشيكات",
    "acc.cheque_reports_desc": "تصفية الشيكات حسب الاتجاه والحالة: آجلة، تحت التحصيل، مودعة، محصلة، مرتجعة، ملغاة.",
    "acc.count": "العدد",
    "acc.total_amount": "إجمالي المبلغ",
    "common.all": "الكل",
    "nav.profit_centers": "مراكز الربحية",
    "nav.year_end_closing": "إقفال نهاية السنة",
    "nav.financial_reports": "التقارير المالية",
    "nav.group.engineering": "الهندسة",
    "nav.engineering_dashboard": "لوحة المعلومات الهندسية",
    "nav.engineering_disciplines": "التخصصات",
    "nav.consultants": "الاستشاريون",
    "nav.design_packages": "حزم التصميم",
    "nav.drawing_categories": "فئات الرسومات",
    "nav.technical_specifications": "المواصفات الفنية",
    "nav.drawings": "الرسومات",
    "nav.drawing_revisions": "مراجعات الرسومات",
    "nav.boqs": "جداول الكميات",
    "nav.boq_items": "بنود الكميات",
    "nav.boq_quantity_revisions": "مراجعات كميات الجدول",
    "nav.cost_estimates": "تقديرات التكلفة",
    "nav.inspection_requests": "طلبات الفحص",
    "nav.inspection_reports": "تقارير الفحص",
    "nav.defects": "العيوب",
    "nav.corrective_actions": "الإجراءات التصحيحية",
    "nav.rfis": "طلبات المعلومات",
    "nav.technical_submittals": "التقديمات الفنية",
    "nav.material_submittals": "تقديمات المواد",
    "nav.consultant_responses": "ردود الاستشاري",
    "nav.engineering_progress": "التقدم الهندسي",
    "eng.drawings_count": "إجمالي الرسومات",
    "eng.pending_drawing_approvals": "اعتمادات الرسومات المعلقة",
    "eng.boq_count": "جداول الكميات",
    "eng.total_boq_value": "إجمالي قيمة الجداول",
    "eng.open_rfis": "طلبات المعلومات المفتوحة",
    "eng.open_defects": "العيوب المفتوحة",
    "eng.open_inspections": "الفحوصات المفتوحة",
    "eng.consultants_count": "الاستشاريون",
    "eng.drawings_by_status": "الرسومات حسب حالة الاعتماد",
    "eng.defects_by_severity": "العيوب حسب الخطورة",
    "eng.no_data": "لا توجد بيانات",
    "nav.group.construction": "تنفيذ الإنشاءات",
    "nav.construction_dashboard": "لوحة معلومات التنفيذ",
    "nav.contractors": "المقاولون",
    "nav.contractor_contracts": "عقود المقاولين",
    "nav.contract_boq_items": "بنود كميات العقد",
    "nav.work_progress_updates": "تحديثات تقدم الأعمال",
    "nav.payment_certificates": "مستخلصات المقاولين",
    "nav.certificate_items": "بنود المستخلص",
    "nav.certificate_statuses": "حالات المستخلص",
    "nav.certificate_approvals": "اعتماد المستخلص",
    "nav.certificate_approval_logs": "سجل اعتماد المستخلص",
    "nav.variation_orders": "أوامر التغيير",
    "nav.contractor_deductions": "خصومات المقاول",
    "nav.contractor_additions": "إضافات المقاول",
    "nav.retentions": "المحتجزات",
    "nav.advance_payments": "الدفعات المقدمة",
    "nav.advance_recoveries": "استردادات الدفعات المقدمة",
    "nav.contractor_invoices": "فواتير المقاول",
    "nav.contract_approvals": "اعتمادات العقد",
    "nav.construction_reports": "تقارير التنفيذ",
    "con.contracts_count": "إجمالي العقود",
    "con.active_contracts": "العقود النشطة",
    "con.total_contract_value": "إجمالي قيمة العقود",
    "con.total_certified": "إجمالي المعتمد",
    "con.total_deductions": "إجمالي الخصومات",
    "con.total_additions": "إجمالي الإضافات",
    "con.retention_held": "المحتجز",
    "con.open_variations": "أوامر التغيير المفتوحة",
    "con.pending_approvals": "الاعتمادات المعلقة",
    "con.pending_invoices": "الفواتير المعلقة",
    "con.contracts_by_status": "العقود حسب الحالة",
    "con.certificates_by_status": "الشهادات حسب الحالة",
    "con.no_data": "لا توجد بيانات",
    "con.reports": "تقارير التنفيذ",
    "con.reports_subtitle": "ملخصات مالية عبر المقاولين والعقود",
    "con.report_contract_financials": "الملخص المالي للعقود",
    "con.report_certificates": "سجل المستخلصات",
    "con.report_retention": "ملخص المحتجزات",
    "con.report_advances": "ملخص الدفعات المقدمة",
    "con.report_certificate_register": "سجل المستخلصات",
    "con.report_outstanding_certificates": "المستخلصات المستحقة",
    "con.report_certificate_retention": "تقرير محتجزات المستخلصات",
    "con.report_advance_recovery": "تقرير استرداد الدفعات المقدمة",
    "con.contract": "العقد",
    "con.contractor": "المقاول",
    "con.certified": "المعتمد",
    "con.net": "الصافي",
    "con.gross": "الإجمالي",
    "con.retained": "المحتجز",
    "con.released": "المُفرَج عنه",
    "con.recovered": "المُسترَد",
    "con.count": "العدد",
    "con.total": "الإجمالي",
    "con.date": "التاريخ",
    "con.amount": "المبلغ",
    "con.outstanding": "المتبقي",
    "nav.group.procurement": "المشتريات",
    "nav.procurement_dashboard": "لوحة معلومات المشتريات",
    "nav.supplier_categories": "فئات الموردين",
    "nav.suppliers": "الموردون",
    "nav.supplier_contacts": "جهات اتصال الموردين",
    "nav.supplier_evaluations": "تقييمات الموردين",
    "nav.purchase_requests": "طلبات الشراء",
    "nav.purchase_request_items": "بنود طلب الشراء",
    "nav.rfqs": "طلبات عروض الأسعار",
    "nav.rfq_items": "بنود طلب عرض السعر",
    "nav.rfq_suppliers": "موردو طلب عرض السعر",
    "nav.supplier_quotations": "عروض أسعار الموردين",
    "nav.quotation_items": "بنود عرض السعر",
    "nav.purchase_orders": "أوامر الشراء",
    "nav.purchase_order_items": "بنود أمر الشراء",
    "nav.purchase_contracts": "عقود الشراء",
    "nav.purchase_contract_amendments": "تعديلات عقد الشراء",
    "nav.goods_receipt_notes": "سندات استلام البضائع",
    "nav.grn_items": "بنود سند الاستلام",
    "nav.purchase_returns": "مرتجعات الشراء",
    "nav.purchase_return_items": "بنود مرتجع الشراء",
    "nav.procurement_approvals": "اعتمادات المشتريات",
    "nav.procurement_reports": "تقارير المشتريات",
    "nav.group.inventory": "المخزون",
    "nav.inventory_dashboard": "لوحة معلومات المخزون",
    "nav.warehouses": "المستودعات",
    "nav.warehouse_locations": "مواقع المستودعات",
    "nav.item_categories": "فئات الأصناف",
    "nav.item_groups": "مجموعات الأصناف",
    "nav.units_of_measure": "وحدات القياس",
    "nav.inventory_items": "أصناف المخزون",
    "nav.reorder_levels": "مستويات إعادة الطلب",
    "nav.stock_opening_balances": "الأرصدة الافتتاحية للمخزون",
    "nav.goods_receipts": "استلام المخزون",
    "nav.goods_receipt_items": "بنود استلام المخزون",
    "nav.goods_issues": "صرف المخزون",
    "nav.goods_issue_items": "بنود صرف المخزون",
    "nav.inventory_transfers": "تحويلات المخزون",
    "nav.inventory_transfer_items": "بنود تحويلات المخزون",
    "nav.stock_adjustments": "تسويات المخزون",
    "nav.stock_adjustment_items": "بنود تسويات المخزون",
    "nav.stock_counts": "جرد المخزون",
    "nav.stock_count_items": "بنود جرد المخزون",
    "nav.inventory_ledger": "دفتر أستاذ المخزون",
    "nav.inventory_reports": "تقارير المخزون",
    "inv.items_count": "إجمالي الأصناف",
    "inv.active_items": "الأصناف النشطة",
    "inv.warehouses_count": "المستودعات",
    "inv.low_stock_items": "أصناف منخفضة المخزون",
    "inv.total_stock_value": "إجمالي قيمة المخزون",
    "inv.pending_receipts": "استلامات معلقة",
    "inv.pending_issues": "صرفيات معلقة",
    "inv.pending_transfers": "تحويلات معلقة",
    "inv.pending_adjustments": "تسويات معلقة",
    "inv.receipts_by_status": "الاستلامات حسب الحالة",
    "inv.issues_by_status": "الصرفيات حسب الحالة",
    "inv.no_data": "لا توجد بيانات متاحة",
    "inv.reports": "تقارير المخزون",
    "inv.reports_subtitle": "ملخصات حركة المخزون والتقييم",
    "inv.report_receipts": "ملخص استلام المخزون",
    "inv.report_issues": "ملخص صرف المخزون",
    "inv.report_adjustments": "ملخص تسويات المخزون",
    "inv.report_opening": "ملخص الأرصدة الافتتاحية",
    "inv.count": "العدد",
    "inv.total": "الإجمالي",
    "proc.suppliers_count": "إجمالي الموردين",
    "proc.active_suppliers": "الموردون النشطون",
    "proc.open_rfqs": "طلبات عروض الأسعار المفتوحة",
    "proc.pending_requests": "طلبات الشراء المعلقة",
    "proc.open_purchase_orders": "أوامر الشراء المفتوحة",
    "proc.purchase_volume": "حجم المشتريات",
    "proc.total_contract_value": "إجمالي قيمة العقود",
    "proc.pending_approvals": "الاعتمادات المعلقة",
    "proc.pending_returns": "المرتجعات المعلقة",
    "proc.purchase_orders_by_status": "أوامر الشراء حسب الحالة",
    "proc.requests_by_status": "الطلبات حسب الحالة",
    "proc.no_data": "لا توجد بيانات",
    "proc.reports": "تقارير المشتريات",
    "proc.reports_subtitle": "ملخصات مالية عبر الموردين والمشتريات",
    "proc.report_supplier_volume": "حجم مشتريات الموردين",
    "proc.report_orders": "ملخص أوامر الشراء",
    "proc.report_receipts": "ملخص استلام البضائع",
    "proc.report_returns": "ملخص مرتجعات الشراء",
    "proc.supplier": "المورد",
    "proc.count": "العدد",
    "proc.total": "الإجمالي",
    "acc.account": "الحساب",
    "acc.parent": "الحساب الأب",
    "acc.parent_cost_center": "مركز التكلفة الأب",
    "acc.type": "النوع",
    "acc.normal_side": "الطبيعة",
    "acc.postable": "قابل للترحيل",
    "acc.kind": "النوع",
    "acc.period": "الفترة",
    "acc.period_number": "رقم الفترة",
    "acc.start_date": "تاريخ البداية",
    "acc.end_date": "تاريخ النهاية",
    "acc.entry_date": "تاريخ القيد",
    "acc.reference": "المرجع",
    "acc.description": "الوصف",
    "acc.direction": "الاتجاه",
    "acc.cheque_number": "رقم الشيك",
    "acc.cheque_date": "تاريخ الشيك",
    "acc.due_date": "تاريخ الاستحقاق",
    "acc.bank_name": "اسم البنك",
    "acc.payee_name": "اسم المستفيد",
    "acc.change_status": "تغيير الحالة",
    "acc.return_reason": "سبب الإرجاع",
    "acc.action_date": "تاريخ الإجراء",
    "acc.related_unit": "الوحدة المرتبطة",
    "acc.related_installment": "القسط المرتبط",
    "acc.collection_date": "تاريخ التحصيل",
    "acc.attachments": "المرفقات",
    "acc.from_status": "من حالة",
    "acc.to_status": "إلى حالة",
    "acc.actor": "المنفذ",
    "acc.action": "الإجراء",
    "acc.cheques_pending": "شيكات معلقة",
    "acc.cheques_cleared": "شيكات محصلة",
    "acc.cheques_due": "شيكات مستحقة (المبلغ)",
    "acc.close_year": "إقفال السنة",
    "acc.reopen_year": "إعادة فتح السنة",
    "acc.closing_date": "تاريخ الإقفال",
    "acc.reports_hub_subtitle": "إنشاء وتصدير القوائم المالية",
    "acc.open_report": "فتح التقرير",
    "acc.debit": "مدين",
    "acc.credit": "دائن",
    "acc.total_debit": "إجمالي المدين",
    "acc.total_credit": "إجمالي الدائن",
    "acc.balance": "الرصيد",
    "acc.opening_balance": "الرصيد الافتتاحي",
    "acc.closing_balance": "الرصيد الختامي",
    "acc.lines": "البنود",
    "acc.add_line": "إضافة بند",
    "acc.balanced": "متوازن",
    "acc.not_balanced": "غير متوازن",
    "export.excel": "تصدير إلى إكسل",
    "export.pdf": "تصدير إلى PDF",
    "export.generated": "تاريخ الإصدار",
    "export.period": "الفترة",
    "export.from": "من",
    "export.to": "إلى",
    "export.as_of": "كما في",
    "acc.post": "ترحيل",
    "acc.reverse": "عكس",
    "acc.approve": "اعتماد",
    "acc.close": "إقفال",
    "acc.reopen": "إعادة فتح",
    "acc.new_entry": "قيد يومية جديد",
    "acc.event_key": "مفتاح الحدث",
    "acc.debit_account": "الحساب المدين",
    "acc.credit_account": "الحساب الدائن",
    "acc.budget": "الموازنة",
    "acc.fiscal_year": "السنة المالية",
    "acc.amount": "المبلغ",
    "acc.from_date": "من تاريخ",
    "acc.to_date": "إلى تاريخ",
    "acc.as_of_date": "كما في تاريخ",
    "acc.run_report": "تشغيل التقرير",
    "acc.assets": "الأصول",
    "acc.liabilities": "الالتزامات",
    "acc.equity": "حقوق الملكية",
    "acc.total_assets": "إجمالي الأصول",
    "acc.total_liabilities": "إجمالي الالتزامات",
    "acc.total_equity": "إجمالي حقوق الملكية",
    "acc.revenue": "الإيرادات",
    "acc.expenses": "المصروفات",
    "acc.total_revenue": "إجمالي الإيرادات",
    "acc.total_expenses": "إجمالي المصروفات",
    "acc.net_income": "صافي الدخل",
    "acc.operating": "تشغيلية",
    "acc.investing": "استثمارية",
    "acc.financing": "تمويلية",
    "acc.net_change": "صافي التغير",
    "acc.opening_cash": "النقد الافتتاحي",
    "acc.closing_cash": "النقد الختامي",
    "acc.budgeted": "المُوازَن",
    "acc.actual": "الفعلي",
    "acc.variance": "الانحراف",
    "acc.select_account": "اختر حساباً",
    "acc.select_budget": "اختر موازنة",
    "acc.no_data": "لا توجد بيانات للمعايير المحددة",
    "acc.recent_entries": "أحدث القيود اليومية",
    "acc.draft_entries": "قيود مسودة",
    "acc.posted_entries": "قيود مرحّلة",
    "acc.open_periods": "فترات مفتوحة",
    "acc.entry_count": "إجمالي القيود",
    "acc.select_account_prompt": "اختر حسابًا لعرض دفتر الأستاذ الخاص به.",
    "acc.automatic": "تلقائي",
    "acc.export": "تصدير",
    "acc.export_excel": "تصدير إلى Excel",
    "acc.export_pdf": "تصدير إلى PDF",
    "acc.generated": "تاريخ الإصدار",
    "acc.all_dates": "كل التواريخ",
    "acc.cancel": "إلغاء",
    "nav.group.invoicing": "الفوترة والمستحقات",
    "nav.tax_codes": "رموز الضريبة",
    "nav.customer_invoices": "فواتير العملاء",
    "nav.supplier_invoices": "فواتير الموردين",
    "nav.payment_vouchers": "سندات الصرف",
    "nav.ar_aging": "أعمار ذمم العملاء",
    "nav.ap_aging": "أعمار ذمم الموردين",
    "nav.tax_report": "تقرير الضريبة",
    "tax.name": "الاسم",
    "tax.name_ar": "الاسم (عربي)",
    "tax.type": "النوع",
    "tax.rate": "النسبة (%)",
    "tax.account": "حساب الضريبة",
    "tax.code": "رمز الضريبة",
    "tax.base": "المبلغ الأساسي",
    "tax.tax": "مبلغ الضريبة",
    "tax.output_tax": "ضريبة المخرجات",
    "tax.input_tax": "ضريبة المدخلات",
    "tax.net_tax": "صافي الضريبة",
    "aging.party": "الطرف",
    "aging.current": "حالي",
    "aging.days30": "1-30 يوم",
    "aging.days60": "31-60 يوم",
    "aging.days90": "61-90 يوم",
    "aging.days120": "91+ يوم",
    "inv.customer": "العميل",
    "inv.supplier": "المورّد",
    "inv.contract": "العقد",
    "inv.invoice_date": "تاريخ الفاتورة",
    "inv.supplier_invoice_number": "رقم فاتورة المورّد",
    "inv.lines": "البنود",
    "inv.line_description": "الوصف",
    "inv.qty": "الكمية",
    "inv.unit_price": "سعر الوحدة",
    "inv.revenue_account": "حساب الإيراد",
    "inv.expense_account": "حساب المصروف",
    "inv.line_total": "إجمالي البند",
    "inv.add_line": "إضافة بند",
    "inv.subtotal": "المجموع الفرعي",
    "inv.tax_total": "الضريبة",
    "inv.paid": "المدفوع",
    "inv.new_customer_invoice": "فاتورة عميل جديدة",
    "inv.new_supplier_invoice": "فاتورة مورّد جديدة",
    "inv.no_lines": "أضف بنداً واحداً على الأقل",
    "pv.new_voucher": "سند صرف جديد",
    "pv.payee_type": "نوع المستفيد",
    "pv.contractor": "المقاول",
    "pv.payee": "المستفيد",
    "pv.payment_date": "تاريخ الدفع",
    "pv.payment_method": "طريقة الدفع",
    "pv.allocations": "تخصيصات الفواتير",
    "pv.add_allocation": "إضافة تخصيص",
  },
};

export function LanguageProvider({
  children,
  defaultLanguage = "en",
  storageKey = "erp-language",
  ...props
}: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(
    () => (localStorage.getItem(storageKey) as Language) || defaultLanguage
  );

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [dir, language]);

  const setLanguage = (lang: Language) => {
    localStorage.setItem(storageKey, lang);
    setLanguageState(lang);
  };

  const t = (key: string) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageProviderContext.Provider {...props} value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageProviderContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageProviderContext);
  if (context === undefined)
    throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};
