import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "ar";

type LanguageProviderProps = {
  children: React.ReactNode;
  defaultLanguage?: Language;
  storageKey?: string;
};

type LanguageProviderState = {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
};

const initialState: LanguageProviderState = {
  language: "en",
  setLanguage: () => null,
  dir: "ltr",
  t: (key) => key,
};

const LanguageProviderContext = createContext<LanguageProviderState>(initialState);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "login.title": "Sign In",
    "login.subtitle": "Enter your credentials to access the ERP.",
    "login.username": "Username",
    "login.password": "Password",
    "login.submit": "Sign In",
    "login.defaultCredentials": "Default super administrator credentials",
    "nav.dashboard": "Dashboard",
    "nav.users": "Users",
    "nav.roles": "Roles",
    "nav.companies": "Companies",
    "nav.branches": "Branches",
    "nav.fiscal_years": "Fiscal Years",
    "nav.currencies": "Currencies",
    "nav.number_sequences": "Number Sequences",
    "nav.audit_logs": "Audit Logs",
    "nav.login_history": "Login History",
    "nav.settings": "Settings",
    "nav.change_password": "Change Password",
    "nav.logout": "Logout",
    "nav.group.general": "General",
    "nav.group.real_estate": "Real Estate",
    "nav.group.unit_management": "Unit Management",
    "nav.group.crm": "CRM",
    "nav.group.customers": "Customers",
    "nav.group.sales": "Sales",
    "nav.group.installments": "Installments",
    "nav.group.finance": "Finance & Collections",
    "nav.group.administration": "Administration",
    "nav.projects": "Projects",
    "nav.phases": "Phases",
    "nav.buildings": "Buildings",
    "nav.floors": "Floors",
    "nav.units": "Units",
    "nav.unit_types": "Unit Types",
    "nav.unit_statuses": "Unit Statuses",
    "nav.unit_price_lists": "Price Lists",
    "nav.unit_pricing": "Unit Pricing",
    "nav.unit_discounts": "Discounts",
    "nav.leads": "Leads",
    "nav.lead_sources": "Lead Sources",
    "nav.lead_activities": "Lead Activities",
    "nav.lead_follow_ups": "Follow-ups",
    "nav.lead_assignments": "Assignments",
    "nav.lead_conversions": "Conversions",
    "nav.customers": "Customers",
    "nav.customer_contacts": "Contacts",
    "nav.customer_documents": "Documents",
    "nav.customer_notes": "Notes",
    "nav.reservations": "Reservations",
    "nav.reservation_payments": "Reservation Payments",
    "nav.reservation_notes": "Reservation Notes",
    "nav.reservation_documents": "Reservation Documents",
    "nav.contracts": "Contracts",
    "nav.contract_amendments": "Amendments",
    "nav.contract_cancellations": "Cancellations",
    "nav.contract_notes": "Contract Notes",
    "nav.contract_documents": "Contract Documents",
    "nav.unit_transfers": "Unit Transfers",
    "nav.installment_plans": "Installment Plans",
    "nav.installment_schedules": "Schedules",
    "nav.installment_collections": "Collections",
    "nav.penalty_rules": "Penalty Rules",
    "nav.cashboxes": "Cashboxes",
    "nav.treasury_transactions": "Treasury Transactions",
    "nav.bank_accounts": "Bank Accounts",
    "nav.bank_transactions": "Bank Transactions",
    "nav.receipts": "Receipts",
    "nav.penalties": "Penalties",
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome",
    "dashboard.users": "Users",
    "dashboard.companies": "Companies",
    "dashboard.branches": "Branches",
    "dashboard.roles": "Roles",
    "dashboard.active_sessions": "Active Sessions",
    "dashboard.fiscal_years": "Fiscal Years",
    "dashboard.currencies": "Currencies",
    "dashboard.audit_events": "Audit Events",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.real_estate": "Real Estate Overview",
    "dashboard.projects": "Projects",
    "dashboard.buildings": "Buildings",
    "dashboard.units": "Units",
    "dashboard.available_units": "Available Units",
    "dashboard.reserved_units": "Reserved Units",
    "dashboard.sold_units": "Sold Units",
    "dashboard.leads": "Leads",
    "dashboard.customers": "Customers",
    "dashboard.reservations": "Reservations",
    "dashboard.contracts": "Contracts",
    "dashboard.overdue_installments": "Overdue Installments",
    "dashboard.total_contract_value": "Total Contract Value",
    "dashboard.finance": "Finance & Collections",
    "dashboard.total_sales": "Total Sales",
    "dashboard.total_collections": "Total Collections",
    "dashboard.outstanding_installments": "Outstanding Installments",
    "dashboard.overdue_amount": "Overdue Amount",
    "dashboard.treasury_balance": "Treasury Balance",
    "dashboard.bank_balance": "Bank Balance",
    "dashboard.receipts": "Receipts",
    "dashboard.pending_penalties": "Pending Penalties",
    "common.actions": "Actions",
    "common.create": "Create",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.search": "Search...",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.locked": "Locked",
    "common.open": "Open",
    "common.closed": "Closed",
    "common.loading": "Loading...",
    "common.no_results": "No records found",
    "common.total": "Total",
    "common.created": "Created successfully",
    "common.saved": "Saved successfully",
    "common.deleted": "Deleted successfully",
    "common.error": "Something went wrong",
    "users.title": "Users",
    "users.create": "Create User",
    "users.edit": "Edit User",
    "users.delete_confirm": "Are you sure you want to delete this user?",
    "roles.title": "Roles",
    "roles.create": "Create Role",
    "companies.title": "Companies",
    "companies.create": "Create Company",
    "branches.title": "Branches",
    "branches.create": "Create Branch",
    "fiscal_years.title": "Fiscal Years",
    "fiscal_years.create": "Create Fiscal Year",
    "currencies.title": "Currencies",
    "currencies.create": "Create Currency",
    "number_sequences.title": "Number Sequences",
    "number_sequences.create": "Create Number Sequence",
    "audit_logs.title": "Audit Logs",
    "login_history.title": "Login History",
    "settings.title": "Settings",
    "change_password.title": "Change Password",
    "change_password.current": "Current Password",
    "change_password.new": "New Password",
    "change_password.confirm": "Confirm New Password",
    "change_password.submit": "Change Password",
    "change_password.success": "Password changed successfully",
    "change_password.error": "Failed to change password",
    "common.update": "Update",
    "common.delete_confirm": "Are you sure you want to delete this record?",
    "common.code": "Code",
    "common.name": "Name",
    "common.name_ar": "Name (Arabic)",
    "common.email": "Email",
    "common.username": "Username",
    "common.password": "Password",
    "common.company": "Company",
    "common.manager": "Manager",
    "common.description": "Description",
    "common.type": "Type",
    "common.symbol": "Symbol",
    "common.start_date": "Start Date",
    "common.end_date": "End Date",
    "common.user": "User",
    "common.timestamp": "Timestamp",
    "common.action": "Action",
    "common.entity": "Entity",
    "common.details": "Details",
    "common.success": "Success",
    "common.failed": "Failed",
    "roles.system": "System",
    "roles.users": "Users",
    "roles.permissions": "Permissions",
    "branches.filter_company": "Filter by company",
    "branches.select_company": "Select a company",
    "currencies.base": "Base",
    "currencies.code_hint": "Code (e.g. SAR)",
    "number_sequences.prefix": "Prefix",
    "number_sequences.next": "Next",
    "number_sequences.sample": "Sample",
    "number_sequences.padding": "Padding",
    "audit_logs.filter_entity": "Filter by entity (e.g. users)",
    "audit_logs.filter_action": "Filter by action (e.g. update)",
    "login_history.ip": "IP Address",
    "login_history.user_agent": "User Agent",
    "settings.saved": "Settings saved successfully",
    "settings.save_failed": "Failed to save settings",
    "change_password.mismatch": "New passwords do not match",
    "change_password.req_length": "Password must be at least 8 characters long",
    "change_password.req_upper": "Password must contain at least one uppercase letter",
    "change_password.req_lower": "Password must contain at least one lowercase letter",
    "change_password.req_number": "Password must contain at least one number",
    "change_password.hint": "Min 8 chars, 1 uppercase, 1 lowercase, 1 number",
    "common.name_en": "Name (English)",
    "common.full_name": "Full Name",
    "branches.all_companies": "All Companies",
    "fiscal_years.name_hint": "Name (e.g. 2026)",
    "number_sequences.document_type": "Document Type",
    "number_sequences.prefix_hint": "Prefix (e.g. INV-)",
    "number_sequences.next_number": "Next Number",
    "number_sequences.reset_yearly": "Reset counter yearly",
    "not_found.title": "Page Not Found",
    "not_found.message": "The page you are looking for does not exist.",
  },
  ar: {
    "login.title": "تسجيل الدخول",
    "login.subtitle": "أدخل بيانات الاعتماد الخاصة بك للوصول.",
    "login.username": "اسم المستخدم",
    "login.password": "كلمة المرور",
    "login.submit": "تسجيل الدخول",
    "login.defaultCredentials": "بيانات اعتماد المسؤول الأعلى الافتراضية",
    "nav.dashboard": "لوحة القيادة",
    "nav.users": "المستخدمين",
    "nav.roles": "الأدوار",
    "nav.companies": "الشركات",
    "nav.branches": "الفروع",
    "nav.fiscal_years": "السنوات المالية",
    "nav.currencies": "العملات",
    "nav.number_sequences": "التسلسلات الرقمية",
    "nav.audit_logs": "سجلات التدقيق",
    "nav.login_history": "سجل تسجيل الدخول",
    "nav.settings": "الإعدادات",
    "nav.change_password": "تغيير كلمة المرور",
    "nav.logout": "تسجيل الخروج",
    "nav.group.general": "عام",
    "nav.group.real_estate": "العقارات",
    "nav.group.unit_management": "إدارة الوحدات",
    "nav.group.crm": "إدارة العلاقات",
    "nav.group.customers": "العملاء",
    "nav.group.sales": "المبيعات",
    "nav.group.installments": "الأقساط",
    "nav.group.finance": "المالية والتحصيلات",
    "nav.group.administration": "الإدارة",
    "nav.projects": "المشاريع",
    "nav.phases": "المراحل",
    "nav.buildings": "المباني",
    "nav.floors": "الطوابق",
    "nav.units": "الوحدات",
    "nav.unit_types": "أنواع الوحدات",
    "nav.unit_statuses": "حالات الوحدات",
    "nav.unit_price_lists": "قوائم الأسعار",
    "nav.unit_pricing": "تسعير الوحدات",
    "nav.unit_discounts": "الخصومات",
    "nav.leads": "العملاء المحتملون",
    "nav.lead_sources": "مصادر العملاء",
    "nav.lead_activities": "الأنشطة",
    "nav.lead_follow_ups": "المتابعات",
    "nav.lead_assignments": "التعيينات",
    "nav.lead_conversions": "التحويلات",
    "nav.customers": "العملاء",
    "nav.customer_contacts": "جهات الاتصال",
    "nav.customer_documents": "المستندات",
    "nav.customer_notes": "الملاحظات",
    "nav.reservations": "الحجوزات",
    "nav.reservation_payments": "مدفوعات الحجز",
    "nav.reservation_notes": "ملاحظات الحجوزات",
    "nav.reservation_documents": "مستندات الحجوزات",
    "nav.contracts": "العقود",
    "nav.contract_amendments": "تعديلات العقود",
    "nav.contract_cancellations": "إلغاءات العقود",
    "nav.contract_notes": "ملاحظات العقود",
    "nav.contract_documents": "مستندات العقود",
    "nav.unit_transfers": "نقل الوحدات",
    "nav.installment_plans": "خطط الأقساط",
    "nav.installment_schedules": "جداول الأقساط",
    "nav.installment_collections": "التحصيلات",
    "nav.penalty_rules": "قواعد الغرامات",
    "nav.cashboxes": "الخزائن",
    "nav.treasury_transactions": "حركات الخزينة",
    "nav.bank_accounts": "الحسابات البنكية",
    "nav.bank_transactions": "الحركات البنكية",
    "nav.receipts": "سندات القبض",
    "nav.penalties": "الغرامات",
    "dashboard.title": "لوحة القيادة",
    "dashboard.welcome": "مرحباً",
    "dashboard.users": "المستخدمين",
    "dashboard.companies": "الشركات",
    "dashboard.branches": "الفروع",
    "dashboard.roles": "الأدوار",
    "dashboard.active_sessions": "الجلسات النشطة",
    "dashboard.fiscal_years": "السنوات المالية",
    "dashboard.currencies": "العملات",
    "dashboard.audit_events": "أحداث التدقيق",
    "dashboard.recent_activity": "النشاط الأخير",
    "dashboard.real_estate": "نظرة عامة على العقارات",
    "dashboard.projects": "المشاريع",
    "dashboard.buildings": "المباني",
    "dashboard.units": "الوحدات",
    "dashboard.available_units": "الوحدات المتاحة",
    "dashboard.reserved_units": "الوحدات المحجوزة",
    "dashboard.sold_units": "الوحدات المباعة",
    "dashboard.leads": "العملاء المحتملون",
    "dashboard.customers": "العملاء",
    "dashboard.reservations": "الحجوزات",
    "dashboard.contracts": "العقود",
    "dashboard.overdue_installments": "الأقساط المتأخرة",
    "dashboard.total_contract_value": "إجمالي قيمة العقود",
    "dashboard.finance": "المالية والتحصيلات",
    "dashboard.total_sales": "إجمالي المبيعات",
    "dashboard.total_collections": "إجمالي التحصيلات",
    "dashboard.outstanding_installments": "الأقساط المستحقة",
    "dashboard.overdue_amount": "المبلغ المتأخر",
    "dashboard.treasury_balance": "رصيد الخزينة",
    "dashboard.bank_balance": "الرصيد البنكي",
    "dashboard.receipts": "سندات القبض",
    "dashboard.pending_penalties": "غرامات معلقة",
    "common.actions": "الإجراءات",
    "common.create": "إنشاء",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.search": "بحث...",
    "common.status": "الحالة",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.locked": "مغلق",
    "common.open": "مفتوح",
    "common.closed": "مغلق",
    "common.loading": "جار التحميل...",
    "common.no_results": "لا توجد سجلات",
    "common.total": "الإجمالي",
    "common.created": "تم الإنشاء بنجاح",
    "common.saved": "تم الحفظ بنجاح",
    "common.deleted": "تم الحذف بنجاح",
    "common.error": "حدث خطأ ما",
    "users.title": "المستخدمين",
    "users.create": "إنشاء مستخدم",
    "users.edit": "تعديل مستخدم",
    "users.delete_confirm": "هل أنت متأكد أنك تريد حذف هذا المستخدم؟",
    "roles.title": "الأدوار",
    "roles.create": "إنشاء دور",
    "companies.title": "الشركات",
    "companies.create": "إنشاء شركة",
    "branches.title": "الفروع",
    "branches.create": "إنشاء فرع",
    "fiscal_years.title": "السنوات المالية",
    "fiscal_years.create": "إنشاء سنة مالية",
    "currencies.title": "العملات",
    "currencies.create": "إنشاء عملة",
    "number_sequences.title": "التسلسلات الرقمية",
    "number_sequences.create": "إنشاء تسلسل رقمي",
    "audit_logs.title": "سجلات التدقيق",
    "login_history.title": "سجل تسجيل الدخول",
    "settings.title": "الإعدادات",
    "change_password.title": "تغيير كلمة المرور",
    "change_password.current": "كلمة المرور الحالية",
    "change_password.new": "كلمة المرور الجديدة",
    "change_password.confirm": "تأكيد كلمة المرور الجديدة",
    "change_password.submit": "تغيير كلمة المرور",
    "change_password.success": "تم تغيير كلمة المرور بنجاح",
    "change_password.error": "فشل في تغيير كلمة المرور",
    "common.update": "تحديث",
    "common.delete_confirm": "هل أنت متأكد من حذف هذا السجل؟",
    "common.code": "الكود",
    "common.name": "الاسم",
    "common.name_ar": "الاسم (عربي)",
    "common.email": "البريد الإلكتروني",
    "common.username": "اسم المستخدم",
    "common.password": "كلمة المرور",
    "common.company": "الشركة",
    "common.manager": "المدير",
    "common.description": "الوصف",
    "common.type": "النوع",
    "common.symbol": "الرمز",
    "common.start_date": "تاريخ البداية",
    "common.end_date": "تاريخ النهاية",
    "common.user": "المستخدم",
    "common.timestamp": "الطابع الزمني",
    "common.action": "الإجراء",
    "common.entity": "الكيان",
    "common.details": "التفاصيل",
    "common.success": "نجاح",
    "common.failed": "فشل",
    "roles.system": "نظام",
    "roles.users": "المستخدمون",
    "roles.permissions": "الصلاحيات",
    "branches.filter_company": "تصفية حسب الشركة",
    "branches.select_company": "اختر شركة",
    "currencies.base": "أساسية",
    "currencies.code_hint": "الرمز (مثل SAR)",
    "number_sequences.prefix": "البادئة",
    "number_sequences.next": "التالي",
    "number_sequences.sample": "نموذج",
    "number_sequences.padding": "عدد الخانات",
    "audit_logs.filter_entity": "تصفية حسب الكيان (مثل users)",
    "audit_logs.filter_action": "تصفية حسب الإجراء (مثل update)",
    "login_history.ip": "عنوان IP",
    "login_history.user_agent": "وكيل المستخدم",
    "settings.saved": "تم حفظ الإعدادات بنجاح",
    "settings.save_failed": "فشل حفظ الإعدادات",
    "change_password.mismatch": "كلمتا المرور غير متطابقتين",
    "change_password.req_length": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
    "change_password.req_upper": "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
    "change_password.req_lower": "يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل",
    "change_password.req_number": "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
    "change_password.hint": "8 أحرف على الأقل، حرف كبير، حرف صغير، ورقم",
    "common.name_en": "الاسم (إنجليزي)",
    "common.full_name": "الاسم الكامل",
    "branches.all_companies": "كل الشركات",
    "fiscal_years.name_hint": "الاسم (مثل 2026)",
    "number_sequences.document_type": "نوع المستند",
    "number_sequences.prefix_hint": "البادئة (مثل INV-)",
    "number_sequences.next_number": "الرقم التالي",
    "number_sequences.reset_yearly": "إعادة تعيين العداد سنوياً",
    "not_found.title": "الصفحة غير موجودة",
    "not_found.message": "الصفحة التي تبحث عنها غير موجودة.",
  },
};

export function LanguageProvider({
  children,
  defaultLanguage = "en",
  storageKey = "erp-language",
  ...props
}: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(
    () => (localStorage.getItem(storageKey) as Language) || defaultLanguage
  );

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [dir, language]);

  const setLanguage = (lang: Language) => {
    localStorage.setItem(storageKey, lang);
    setLanguageState(lang);
  };

  const t = (key: string) => translations[language]?.[key] || key;

  return (
    <LanguageProviderContext.Provider {...props} value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageProviderContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageProviderContext);
  if (context === undefined)
    throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};
