import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import rolesRouter from "./roles";
import companiesRouter from "./companies";
import branchesRouter from "./branches";
import fiscalYearsRouter from "./fiscal-years";
import currenciesRouter from "./currencies";
import settingsRouter from "./settings";
import numberSequencesRouter from "./number-sequences";
import auditRouter from "./audit";
import dashboardRouter from "./dashboard";
import realEstateRouter from "./real-estate";
import crmRouter from "./crm";
import customersRouter from "./customers";
import salesRouter from "./sales";
import installmentsRouter from "./installments";
import unitManagementRouter from "./unit-management";
import financeRouter from "./finance";
import chequesRouter from "./cheques";
import accountingRouter from "./accounting";
import arApRouter from "./ar-ap";
import engineeringRouter from "./engineering";
import constructionRouter from "./construction";
import procurementRouter from "./procurement";
import inventoryRouter from "./inventory";
import hrRouter from "./hr";
import legalRouter from "./legal";
import biRouter from "./bi";
import landBankRouter from "./land-bank";
import handoverRouter from "./handover";
import customerServiceRouter from "./customer-service";
import fixedAssetsRouter from "./fixed-assets";
import generalAdminRouter from "./general-admin";
import insuranceRouter from "./insurance";
import masterDataRouter from "./master-data";
import changeRequestsRouter from "./change-requests";
import notificationsRouter from "./notifications";
import executiveOversightRouter from "./executive-oversight";
import formTemplatesRouter from "./form-templates";
import printJobsRouter from "./print-jobs";
import portalRouter from "./portal";
import documentsRouter from "./documents";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
// Portal routes manage their own auth per-route (public auth endpoints +
// requireCustomerAuth). Mount BEFORE the ERP routers, each of which applies a
// router-level requireAuth that would otherwise intercept /portal/* requests.
router.use(portalRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(companiesRouter);
router.use(branchesRouter);
router.use(fiscalYearsRouter);
router.use(currenciesRouter);
router.use(settingsRouter);
router.use(numberSequencesRouter);
router.use(auditRouter);
router.use(dashboardRouter);
router.use(realEstateRouter);
router.use(crmRouter);
router.use(customersRouter);
router.use(salesRouter);
router.use(installmentsRouter);
router.use(unitManagementRouter);
router.use(financeRouter);
router.use(chequesRouter);
router.use(accountingRouter);
router.use(arApRouter);
router.use(engineeringRouter);
router.use(constructionRouter);
router.use(procurementRouter);
router.use(inventoryRouter);
router.use(hrRouter);
router.use(legalRouter);
router.use(biRouter);
router.use(landBankRouter);
router.use(handoverRouter);
router.use(customerServiceRouter);
router.use(fixedAssetsRouter);
router.use(generalAdminRouter);
router.use(insuranceRouter);
router.use(masterDataRouter);
router.use(changeRequestsRouter);
router.use(notificationsRouter);
router.use(executiveOversightRouter);
router.use(documentsRouter);
router.use(formTemplatesRouter);
router.use(printJobsRouter);

export default router;
