export type Lang = "en" | "ar";

export interface LabelPair {
  en: string;
  ar: string;
}

// Central bilingual label registry. This is the single source of truth for the
// short EN/AR labels used by enum-style codes across the ERP. The Master Data
// engine seeds its values from this registry so stored snake_case codes stay
// identical while option lists become data-driven, and the web layer re-exports
// this map (as ENUM_LABELS) for badges/options and as the resolver fallback.
export const LABELS: Record<string, LabelPair> = {
  // customer service ops
  inbound: { en: "Inbound", ar: "وارد" },
  outbound: { en: "Outbound", ar: "صادر" },
  phone: { en: "Phone", ar: "هاتف" },
  whatsapp: { en: "WhatsApp", ar: "واتساب" },
  sms: { en: "SMS", ar: "رسالة نصية" },
  missed: { en: "Missed", ar: "فائتة" },
  no_answer: { en: "No Answer", ar: "بدون رد" },
  voicemail: { en: "Voicemail", ar: "بريد صوتي" },
  manual: { en: "Manual", ar: "يدوي" },
  work_order: { en: "Work Order", ar: "أمر عمل" },
  handover: { en: "Handover", ar: "تسليم" },
  periodic: { en: "Periodic", ar: "دوري" },
  // land bank
  available: { en: "Available", ar: "متاحة" },
  acquired: { en: "Acquired", ar: "مُكتسبة" },
  under_development: { en: "Under Development", ar: "قيد التطوير" },
  developed: { en: "Developed", ar: "مطوّرة" },
  sold: { en: "Sold", ar: "مباعة" },
  freehold: { en: "Freehold", ar: "ملكية تامة" },
  leasehold: { en: "Leasehold", ar: "حق انتفاع طويل" },
  usufruct: { en: "Usufruct", ar: "حق انتفاع" },
  joint: { en: "Joint", ar: "ملكية مشتركة" },
  clear: { en: "Clear", ar: "خالية" },
  disputed: { en: "Disputed", ar: "متنازع عليها" },
  mortgaged: { en: "Mortgaged", ar: "مرهونة" },
  restricted: { en: "Restricted", ar: "مقيّدة" },
  development: { en: "Development", ar: "تطوير" },
  lease: { en: "Lease", ar: "إيجار" },
  reserve: { en: "Reserve", ar: "احتياطي" },
  planned: { en: "Planned", ar: "مخطط" },
  deed: { en: "Title Deed", ar: "صك ملكية" },
  survey: { en: "Survey", ar: "مساحة" },
  permit: { en: "Permit", ar: "تصريح" },
  valuation: { en: "Valuation", ar: "تقييم" },
  inheritance: { en: "Inheritance", ar: "ميراث" },
  grant: { en: "Grant", ar: "منحة" },
  exchange: { en: "Exchange", ar: "مبادلة" },
  cash: { en: "Cash", ar: "نقدي" },
  bank_transfer: { en: "Bank Transfer", ar: "تحويل بنكي" },
  cheque: { en: "Cheque", ar: "شيك" },
  card: { en: "Card", ar: "بطاقة" },
  active: { en: "Active", ar: "نشط" },
  inactive: { en: "Inactive", ar: "غير نشط" },
  closed: { en: "Closed", ar: "مغلق" },
  converted: { en: "Converted", ar: "محوّل" },
  cancelled: { en: "Cancelled", ar: "ملغي" },
  expired: { en: "Expired", ar: "منتهي" },
  pending: { en: "Pending", ar: "قيد الانتظار" },
  paid: { en: "Paid", ar: "مدفوع" },
  partial: { en: "Partial", ar: "جزئي" },
  partially_paid: { en: "Partially Paid", ar: "مدفوع جزئياً" },
  overdue: { en: "Overdue", ar: "متأخر" },
  waived: { en: "Waived", ar: "معفى" },
  confirmed: { en: "Confirmed", ar: "مؤكد" },
  done: { en: "Done", ar: "منجز" },
  individual: { en: "Individual", ar: "فرد" },
  company: { en: "Company", ar: "شركة" },
  fixed: { en: "Fixed", ar: "ثابت" },
  percentage: { en: "Percentage", ar: "نسبة مئوية" },
  in: { en: "In", ar: "وارد" },
  out: { en: "Out", ar: "صادر" },
  output: { en: "Output Tax", ar: "ضريبة مخرجات" },
  input: { en: "Input Tax", ar: "ضريبة مدخلات" },
  exempt: { en: "Exempt", ar: "معفاة" },
  supplier: { en: "Supplier", ar: "مورّد" },
  contractor: { en: "Contractor", ar: "مقاول" },
  planning: { en: "Planning", ar: "تخطيط" },
  completed: { en: "Completed", ar: "مكتمل" },
  on_hold: { en: "On Hold", ar: "معلّق" },
  draft: { en: "Draft", ar: "مسودة" },
  new: { en: "New", ar: "جديد" },
  contacted: { en: "Contacted", ar: "تم التواصل" },
  qualified: { en: "Qualified", ar: "مؤهل" },
  proposal: { en: "Proposal", ar: "عرض" },
  won: { en: "Won", ar: "ناجح" },
  lost: { en: "Lost", ar: "خاسر" },
  monthly: { en: "Monthly", ar: "شهري" },
  quarterly: { en: "Quarterly", ar: "ربع سنوي" },
  semi_annual: { en: "Semi Annual", ar: "نصف سنوي" },
  annual: { en: "Annual", ar: "سنوي" },
  custom: { en: "Custom", ar: "مخصص" },
  note: { en: "Note", ar: "ملاحظة" },
  call: { en: "Call", ar: "اتصال" },
  meeting: { en: "Meeting", ar: "اجتماع" },
  email: { en: "Email", ar: "بريد إلكتروني" },
  visit: { en: "Visit", ar: "زيارة" },
  // accounting: account types
  asset: { en: "Asset", ar: "أصول" },
  liability: { en: "Liability", ar: "التزامات" },
  equity: { en: "Equity", ar: "حقوق ملكية" },
  revenue: { en: "Revenue", ar: "إيرادات" },
  expense: { en: "Expense", ar: "مصروفات" },
  // accounting: normal side
  debit: { en: "Debit", ar: "مدين" },
  credit: { en: "Credit", ar: "دائن" },
  // accounting: journal entry status
  posted: { en: "Posted", ar: "مرحّل" },
  reversed: { en: "Reversed", ar: "معكوس" },
  approved: { en: "Approved", ar: "معتمد" },
  // accounting: cost center kind
  department: { en: "Department", ar: "قسم" },
  project: { en: "Project", ar: "مشروع" },
  branch: { en: "Branch", ar: "فرع" },
  // accounting: profit center kind
  segment: { en: "Segment", ar: "قطاع" },
  // cheques: direction
  incoming: { en: "Incoming", ar: "وارد" },
  outgoing: { en: "Outgoing", ar: "صادر" },
  // cheques: status lifecycle
  post_dated: { en: "Post-dated", ar: "مؤجل الدفع" },
  under_collection: { en: "Under Collection", ar: "قيد التحصيل" },
  deposited: { en: "Deposited", ar: "مودع" },
  cleared: { en: "Cleared", ar: "محصّل" },
  returned: { en: "Returned", ar: "مرتجع" },
  // accounting: fiscal period / budget status
  open: { en: "Open", ar: "مفتوح" },
  // engineering: statuses / types
  in_progress: { en: "In Progress", ar: "قيد التنفيذ" },
  submitted: { en: "Submitted", ar: "مُقدَّم" },
  reviewed: { en: "Reviewed", ar: "مُراجَع" },
  rejected: { en: "Rejected", ar: "مرفوض" },
  superseded: { en: "Superseded", ar: "مُستبدَل" },
  approved_with_comments: { en: "Approved with Comments", ar: "معتمد مع ملاحظات" },
  answered: { en: "Answered", ar: "تمت الإجابة" },
  under_review: { en: "Under Review", ar: "قيد المراجعة" },
  pass: { en: "Pass", ar: "ناجح" },
  fail: { en: "Fail", ar: "راسب" },
  conditional: { en: "Conditional", ar: "مشروط" },
  low: { en: "Low", ar: "منخفض" },
  medium: { en: "Medium", ar: "متوسط" },
  high: { en: "High", ar: "مرتفع" },
  critical: { en: "Critical", ar: "حرج" },
  architectural: { en: "Architectural", ar: "معماري" },
  structural: { en: "Structural", ar: "إنشائي" },
  mep: { en: "MEP", ar: "كهروميكانيكي" },
  rfi: { en: "RFI", ar: "طلب معلومات" },
  technical_submittal: { en: "Technical Submittal", ar: "تقديم فني" },
  material_submittal: { en: "Material Submittal", ar: "تقديم مواد" },
  // construction execution: statuses / types / levels
  verified: { en: "Verified", ar: "مُتحقَّق" },
  suspended: { en: "Suspended", ar: "موقوف" },
  terminated: { en: "Terminated", ar: "منهى" },
  applied: { en: "Applied", ar: "مطبّق" },
  held: { en: "Held", ar: "محتجز" },
  released: { en: "Released", ar: "مُفرَج عنه" },
  partially_released: { en: "Partially Released", ar: "مُفرَج عنه جزئياً" },
  registered: { en: "Registered", ar: "مُسجَّل" },
  recovered: { en: "Recovered", ar: "مُسترَد" },
  addition: { en: "Addition", ar: "إضافة" },
  deduction: { en: "Deduction", ar: "خصم" },
  penalty: { en: "Penalty", ar: "غرامة" },
  delay_penalty: { en: "Delay Penalty", ar: "غرامة تأخير" },
  quality_penalty: { en: "Quality Penalty", ar: "غرامة جودة" },
  other: { en: "Other", ar: "أخرى" },
  extra_work: { en: "Extra Work", ar: "أعمال إضافية" },
  compensation: { en: "Compensation", ar: "تعويض" },
  claim: { en: "Claim", ar: "مطالبة" },
  site_engineer: { en: "Site Engineer", ar: "مهندس موقع" },
  project_manager: { en: "Project Manager", ar: "مدير مشروع" },
  engineering_manager: { en: "Engineering Manager", ar: "مدير هندسي" },
  finance: { en: "Finance", ar: "المالية" },
  // procurement: statuses / classifications / types / levels
  blacklist: { en: "Blacklisted", ar: "قائمة سوداء" },
  local: { en: "Local", ar: "محلي" },
  international: { en: "International", ar: "دولي" },
  manufacturer: { en: "Manufacturer", ar: "مُصنّع" },
  distributor: { en: "Distributor", ar: "موزّع" },
  service_provider: { en: "Service Provider", ar: "مزوّد خدمة" },
  item: { en: "Item", ar: "صنف" },
  service: { en: "Service", ar: "خدمة" },
  urgent: { en: "Urgent", ar: "عاجل" },
  issued: { en: "Issued", ar: "صادر" },
  awarded: { en: "Awarded", ar: "تمت الترسية" },
  invited: { en: "Invited", ar: "مدعو" },
  responded: { en: "Responded", ar: "تم الرد" },
  declined: { en: "Declined", ar: "رفض" },
  received: { en: "Received", ar: "مستلم" },
  under_evaluation: { en: "Under Evaluation", ar: "قيد التقييم" },
  recommended: { en: "Recommended", ar: "موصى به" },
  full: { en: "Full", ar: "كامل" },
  passed: { en: "Passed", ar: "ناجح" },
  failed: { en: "Failed", ar: "فاشل" },
  department_head: { en: "Department Head", ar: "رئيس القسم" },
  procurement_manager: { en: "Procurement Manager", ar: "مدير المشتريات" },
  general_manager: { en: "General Manager", ar: "المدير العام" },
  main: { en: "Main", ar: "رئيسي" },
  transit: { en: "Transit", ar: "عبور" },
  virtual: { en: "Virtual", ar: "افتراضي" },
  quarantine: { en: "Quarantine", ar: "حجر" },
  stock: { en: "Stock", ar: "مخزون" },
  non_stock: { en: "Non-Stock", ar: "غير مخزون" },
  fifo: { en: "FIFO", ar: "الوارد أولاً صادر أولاً" },
  lifo: { en: "LIFO", ar: "الوارد أخيراً صادر أولاً" },
  average: { en: "Average", ar: "المتوسط المرجح" },
  standard: { en: "Standard", ar: "معياري" },
  purchase: { en: "Purchase", ar: "شراء" },
  return: { en: "Return", ar: "مرتجع" },
  transfer: { en: "Transfer", ar: "تحويل" },
  production: { en: "Production", ar: "إنتاج" },
  opening: { en: "Opening", ar: "افتتاحي" },
  consumption: { en: "Consumption", ar: "استهلاك" },
  sale: { en: "Sale", ar: "بيع" },
  disposal: { en: "Disposal", ar: "إتلاف" },
  warehouse: { en: "Warehouse", ar: "مستودع" },
  location: { en: "Location", ar: "موقع" },
  in_transit: { en: "In Transit", ar: "قيد النقل" },
  increase: { en: "Increase", ar: "زيادة" },
  decrease: { en: "Decrease", ar: "نقصان" },
  revaluation: { en: "Revaluation", ar: "إعادة تقييم" },
  damage: { en: "Damage", ar: "تلف" },
  loss: { en: "Loss", ar: "فقدان" },
  expiry: { en: "Expiry", ar: "انتهاء صلاحية" },
  cycle: { en: "Cycle Count", ar: "جرد دوري" },
  spot: { en: "Spot Count", ar: "جرد فوري" },
  receipt: { en: "Receipt", ar: "استلام" },
  issue: { en: "Issue", ar: "صرف" },
  transfer_in: { en: "Transfer In", ar: "تحويل وارد" },
  transfer_out: { en: "Transfer Out", ar: "تحويل صادر" },
  adjustment: { en: "Adjustment", ar: "تسوية" },
  count: { en: "Count", ar: "جرد" },
  // HR: employment types
  full_time: { en: "Full Time", ar: "دوام كامل" },
  part_time: { en: "Part Time", ar: "دوام جزئي" },
  contract: { en: "Contract", ar: "عقد" },
  temporary: { en: "Temporary", ar: "مؤقت" },
  intern: { en: "Intern", ar: "متدرب" },
  // HR: gender / marital status
  male: { en: "Male", ar: "ذكر" },
  female: { en: "Female", ar: "أنثى" },
  single: { en: "Single", ar: "أعزب" },
  married: { en: "Married", ar: "متزوج" },
  divorced: { en: "Divorced", ar: "مطلّق" },
  widowed: { en: "Widowed", ar: "أرمل" },
  // HR: employee / leave statuses
  on_leave: { en: "On Leave", ar: "في إجازة" },
  resigned: { en: "Resigned", ar: "مستقيل" },
  // HR: attendance statuses
  present: { en: "Present", ar: "حاضر" },
  absent: { en: "Absent", ar: "غائب" },
  late: { en: "Late", ar: "متأخر" },
  holiday: { en: "Holiday", ar: "عطلة" },
  weekend: { en: "Weekend", ar: "نهاية الأسبوع" },
  // HR: salary component / payroll
  earning: { en: "Earning", ar: "استحقاق" },
  processing: { en: "Processing", ar: "قيد المعالجة" },
  // HR: loan types / status
  personal: { en: "Personal", ar: "شخصي" },
  housing: { en: "Housing", ar: "سكن" },
  car: { en: "Car", ar: "سيارة" },
  emergency: { en: "Emergency", ar: "طارئ" },
  disbursed: { en: "Disbursed", ar: "مصروف" },
  // HR: evaluation ratings
  excellent: { en: "Excellent", ar: "ممتاز" },
  good: { en: "Good", ar: "جيد" },
  poor: { en: "Poor", ar: "ضعيف" },
  // HR: document types
  id_card: { en: "ID Card", ar: "بطاقة هوية" },
  passport: { en: "Passport", ar: "جواز سفر" },
  visa: { en: "Visa", ar: "تأشيرة" },
  certificate: { en: "Certificate", ar: "شهادة" },
  work_permit: { en: "Work Permit", ar: "تصريح عمل" },
  // Legal: source/contract type, counterparty
  legal: { en: "Legal", ar: "قانوني" },
  sales: { en: "Sales", ar: "مبيعات" },
  construction: { en: "Construction", ar: "إنشاءات" },
  procurement: { en: "Procurement", ar: "مشتريات" },
  employee: { en: "Employee", ar: "موظف" },
  customer: { en: "Customer", ar: "عميل" },
  reservation: { en: "Reservation", ar: "حجز" },
  // Legal: contract lifecycle status
  renewed: { en: "Renewed", ar: "مُجدَّد" },
  // Legal: case type
  civil: { en: "Civil", ar: "مدني" },
  commercial: { en: "Commercial", ar: "تجاري" },
  labor: { en: "Labor", ar: "عمالي" },
  criminal: { en: "Criminal", ar: "جنائي" },
  administrative: { en: "Administrative", ar: "إداري" },
  arbitration: { en: "Arbitration", ar: "تحكيم" },
  // Legal: case role
  plaintiff: { en: "Plaintiff", ar: "مدّعٍ" },
  defendant: { en: "Defendant", ar: "مدّعى عليه" },
  third_party: { en: "Third Party", ar: "طرف ثالث" },
  // Legal: case status
  settled: { en: "Settled", ar: "تمت التسوية" },
  appealed: { en: "Appealed", ar: "مُستأنف" },
  // Legal: hearing status
  scheduled: { en: "Scheduled", ar: "مجدول" },
  adjourned: { en: "Adjourned", ar: "مؤجّل" },
  // Legal: claim type/direction/status
  financial: { en: "Financial", ar: "مالي" },
  contractual: { en: "Contractual", ar: "تعاقدي" },
  damages: { en: "Damages", ar: "تعويضات" },
  by_company: { en: "By Company", ar: "من الشركة" },
  against_company: { en: "Against Company", ar: "ضد الشركة" },
  accepted: { en: "Accepted", ar: "مقبول" },
  // Legal: notice type/status
  warning: { en: "Warning", ar: "إنذار" },
  demand: { en: "Demand", ar: "مطالبة" },
  termination: { en: "Termination", ar: "إنهاء" },
  sent: { en: "Sent", ar: "مُرسل" },
  acknowledged: { en: "Acknowledged", ar: "تم الاستلام" },
  // Legal: advisor type
  internal: { en: "Internal", ar: "داخلي" },
  external: { en: "External", ar: "خارجي" },
  // Unit Handover
  initial: { en: "Initial", ar: "مبدئي" },
  final: { en: "Final", ar: "نهائي" },
  requested: { en: "Requested", ar: "مطلوب" },
  rescheduled: { en: "Rescheduled", ar: "أعيدت جدولته" },
  na: { en: "N/A", ar: "لا ينطبق" },
  resolved: { en: "Resolved", ar: "تم الحل" },
  // Customer Service: channels
  complaint: { en: "Complaint", ar: "شكوى" },
  maintenance: { en: "Maintenance", ar: "صيانة" },
  support: { en: "Support", ar: "دعم" },
  all: { en: "All", ar: "الكل" },
  // Fixed Assets: depreciation methods, statuses, count, disposal types
  straight_line: { en: "Straight Line", ar: "القسط الثابت" },
  declining_balance: { en: "Declining Balance", ar: "القسط المتناقص" },
  under_maintenance: { en: "Under Maintenance", ar: "تحت الصيانة" },
  disposed: { en: "Disposed", ar: "مُستبعد" },
  written_off: { en: "Written Off", ar: "مشطوب" },
  found: { en: "Found", ar: "موجود" },
  missing: { en: "Missing", ar: "مفقود" },
  damaged: { en: "Damaged", ar: "تالف" },
  scrap: { en: "Scrap", ar: "خردة" },
  donation: { en: "Donation", ar: "تبرع" },
  write_off: { en: "Write-off", ar: "شطب" },
  // CRM: customer classification
  interested: { en: "Interested", ar: "مهتم" },
  follow_up: { en: "Follow Up", ar: "متابعة" },
  initial_reservation: { en: "Initial Reservation", ar: "حجز مبدئي" },
  reserved: { en: "Reserved", ar: "محجوز" },
  contracted: { en: "Contracted", ar: "متعاقد" },
  not_interested: { en: "Not Interested", ar: "غير مهتم" },
  postponed: { en: "Postponed", ar: "مؤجل" },
  former: { en: "Former Customer", ar: "عميل سابق" },
  // General Administration: correspondence / meetings / decisions / services / fleet / visitors / circulars / policies
  letter: { en: "Letter", ar: "خطاب" },
  memo: { en: "Memo", ar: "مذكرة" },
  fax: { en: "Fax", ar: "فاكس" },
  replied: { en: "Replied", ar: "تم الرد" },
  archived: { en: "Archived", ar: "مؤرشف" },
  management: { en: "Management", ar: "إدارة" },
  board: { en: "Board", ar: "مجلس الإدارة" },
  committee: { en: "Committee", ar: "لجنة" },
  implemented: { en: "Implemented", ar: "تم التنفيذ" },
  cleaning: { en: "Cleaning", ar: "نظافة" },
  buffet: { en: "Buffet", ar: "بوفيه" },
  security: { en: "Security", ar: "أمن" },
  catering: { en: "Catering", ar: "تموين" },
  sedan: { en: "Sedan", ar: "سيدان" },
  suv: { en: "SUV", ar: "دفع رباعي" },
  pickup: { en: "Pickup", ar: "بيك أب" },
  van: { en: "Van", ar: "فان" },
  bus: { en: "Bus", ar: "حافلة" },
  truck: { en: "Truck", ar: "شاحنة" },
  owned: { en: "Owned", ar: "مملوكة" },
  leased: { en: "Leased", ar: "تأجير تمويلي" },
  rented: { en: "Rented", ar: "مستأجرة" },
  in_use: { en: "In Use", ar: "قيد الاستخدام" },
  out_of_service: { en: "Out of Service", ar: "خارج الخدمة" },
  repair: { en: "Repair", ar: "إصلاح" },
  inspection: { en: "Inspection", ar: "فحص" },
  checked_in: { en: "Checked In", ar: "تم الدخول" },
  checked_out: { en: "Checked Out", ar: "تم الخروج" },
  published: { en: "Published", ar: "منشور" },
  policy: { en: "Policy", ar: "سياسة" },
  regulation: { en: "Regulation", ar: "لائحة" },
  procedure: { en: "Procedure", ar: "إجراء" },
  guideline: { en: "Guideline", ar: "دليل إرشادي" },
  // Insurance Management
  comprehensive: { en: "Comprehensive", ar: "شامل" },
  social_insurance: { en: "Social Insurance", ar: "تأمينات اجتماعية" },
  medical_insurance: { en: "Medical Insurance", ar: "تأمين طبي" },
  exclusion: { en: "Exclusion", ar: "استبعاد" },
  amendment: { en: "Amendment", ar: "تعديل" },
  salary: { en: "Salary", ar: "الراتب" },
  resignation: { en: "Resignation", ar: "استقالة" },
  retirement: { en: "Retirement", ar: "تقاعد" },
  death: { en: "Death", ar: "وفاة" },
  outstanding: { en: "Outstanding", ar: "مستحق" },
  late_payment: { en: "Late Payment", ar: "تأخر سداد" },
  underpayment: { en: "Underpayment", ar: "نقص سداد" },
  reconciled: { en: "Reconciled", ar: "تمت المطابقة" },
  matched: { en: "Matched", ar: "مطابق" },
  unmatched: { en: "Unmatched", ar: "غير مطابق" },
  subcontractor: { en: "Subcontractor", ar: "مقاول باطن" },
  supplier_contractor: { en: "Supplier Contractor", ar: "مقاول مورد" },
  data: { en: "Data", ar: "بيانات" },
  status: { en: "Status", ar: "الحالة" },
};

export interface LookupCategory {
  /** Stable snake_case code used as the lookup_type code. */
  code: string;
  nameEn: string;
  nameAr: string;
  /** Optional grouping module for UI organisation. */
  module?: string;
  /** Value codes (keys of LABELS) seeded for this category, in display order. */
  valueCodes: string[];
}

// Seeded lookup categories. Each value code is a key of LABELS so the engine's
// stored values reuse the exact snake_case codes existing records already hold.
// The resolver falls back to LABELS for any code, so these categories do not need
// to be exhaustive — they describe the admin-managed option lists.
export const LOOKUP_CATEGORIES: LookupCategory[] = [
  // Shared / finance
  { code: "payment_method", nameEn: "Payment Methods", nameAr: "طرق الدفع", module: "finance", valueCodes: ["cash", "bank_transfer", "cheque", "card"] },
  // CRM & Sales
  { code: "lead_status", nameEn: "Lead Statuses", nameAr: "حالات العميل المحتمل", module: "crm", valueCodes: ["new", "contacted", "qualified", "proposal", "won", "lost", "converted"] },
  { code: "lead_activity_type", nameEn: "Lead Activity Types", nameAr: "أنواع نشاط العميل المحتمل", module: "crm", valueCodes: ["note", "call", "meeting", "email", "visit"] },
  { code: "customer_type", nameEn: "Customer Types", nameAr: "أنواع العملاء", module: "crm", valueCodes: ["individual", "company"] },
  { code: "customer_classification", nameEn: "Customer Classifications", nameAr: "تصنيفات العملاء", module: "crm", valueCodes: ["interested", "follow_up", "initial_reservation", "reserved", "contracted", "not_interested", "postponed", "former"] },
  { code: "reservation_status", nameEn: "Reservation Statuses", nameAr: "حالات الحجز", module: "sales", valueCodes: ["draft", "pending", "confirmed", "converted", "cancelled", "expired"] },
  { code: "installment_frequency", nameEn: "Installment Frequencies", nameAr: "تكرار الأقساط", module: "sales", valueCodes: ["monthly", "quarterly", "semi_annual", "annual", "custom"] },
  { code: "installment_status", nameEn: "Installment Statuses", nameAr: "حالات الأقساط", module: "sales", valueCodes: ["pending", "paid", "partial", "partially_paid", "overdue", "waived"] },
  { code: "discount_type", nameEn: "Discount Types", nameAr: "أنواع الخصم", module: "sales", valueCodes: ["fixed", "percentage"] },
  // Accounting
  { code: "account_type", nameEn: "Account Types", nameAr: "أنواع الحسابات", module: "accounting", valueCodes: ["asset", "liability", "equity", "revenue", "expense"] },
  { code: "account_normal_side", nameEn: "Account Normal Sides", nameAr: "الطبيعة المحاسبية", module: "accounting", valueCodes: ["debit", "credit"] },
  { code: "journal_entry_status", nameEn: "Journal Entry Statuses", nameAr: "حالات القيد", module: "accounting", valueCodes: ["draft", "posted", "reversed", "approved"] },
  { code: "cost_center_kind", nameEn: "Cost Center Kinds", nameAr: "أنواع مراكز التكلفة", module: "accounting", valueCodes: ["department", "project", "branch"] },
  { code: "profit_center_kind", nameEn: "Profit Center Kinds", nameAr: "أنواع مراكز الربحية", module: "accounting", valueCodes: ["segment", "branch", "project"] },
  { code: "fiscal_period_status", nameEn: "Fiscal Period Statuses", nameAr: "حالات الفترة المالية", module: "accounting", valueCodes: ["open", "closed"] },
  { code: "tax_type", nameEn: "Tax Types", nameAr: "أنواع الضريبة", module: "accounting", valueCodes: ["output", "input", "exempt"] },
  { code: "cheque_direction", nameEn: "Cheque Directions", nameAr: "اتجاه الشيك", module: "accounting", valueCodes: ["incoming", "outgoing"] },
  { code: "cheque_status", nameEn: "Cheque Statuses", nameAr: "حالات الشيك", module: "accounting", valueCodes: ["post_dated", "under_collection", "deposited", "cleared", "returned", "cancelled"] },
  // Land Bank
  { code: "land_status", nameEn: "Land Statuses", nameAr: "حالات الأرض", module: "landBank", valueCodes: ["available", "acquired", "under_development", "developed", "sold"] },
  { code: "land_ownership_type", nameEn: "Land Ownership Types", nameAr: "أنواع ملكية الأرض", module: "landBank", valueCodes: ["freehold", "leasehold", "usufruct", "joint"] },
  { code: "land_legal_status", nameEn: "Land Legal Statuses", nameAr: "الحالة القانونية للأرض", module: "landBank", valueCodes: ["clear", "disputed", "mortgaged", "restricted"] },
  { code: "land_utilization_type", nameEn: "Land Utilization Types", nameAr: "أنواع استخدام الأرض", module: "landBank", valueCodes: ["development", "lease", "reserve", "planned"] },
  { code: "land_document_type", nameEn: "Land Document Types", nameAr: "أنواع وثائق الأرض", module: "landBank", valueCodes: ["deed", "survey", "permit", "valuation"] },
  { code: "land_acquisition_method", nameEn: "Land Acquisition Methods", nameAr: "طرق اكتساب الأرض", module: "landBank", valueCodes: ["purchase", "inheritance", "grant", "exchange"] },
  // Engineering
  { code: "engineering_discipline", nameEn: "Engineering Disciplines", nameAr: "التخصصات الهندسية", module: "engineering", valueCodes: ["architectural", "structural", "mep"] },
  { code: "inspection_result", nameEn: "Inspection Results", nameAr: "نتائج الفحص", module: "engineering", valueCodes: ["pass", "fail", "conditional"] },
  { code: "submittal_status", nameEn: "Submittal Statuses", nameAr: "حالات التقديم", module: "engineering", valueCodes: ["draft", "submitted", "under_review", "reviewed", "approved", "approved_with_comments", "rejected", "superseded"] },
  // Procurement
  { code: "supplier_type", nameEn: "Supplier Types", nameAr: "أنواع الموردين", module: "procurement", valueCodes: ["local", "international"] },
  { code: "supplier_category_kind", nameEn: "Supplier Category Kinds", nameAr: "تصنيفات الموردين", module: "procurement", valueCodes: ["manufacturer", "distributor", "service_provider", "contractor"] },
  // Inventory
  { code: "item_type", nameEn: "Item Types", nameAr: "أنواع الأصناف", module: "inventory", valueCodes: ["item", "service", "stock", "non_stock"] },
  { code: "costing_method", nameEn: "Costing Methods", nameAr: "طرق التكلفة", module: "inventory", valueCodes: ["fifo", "lifo", "average", "standard"] },
  { code: "warehouse_type", nameEn: "Warehouse Types", nameAr: "أنواع المستودعات", module: "inventory", valueCodes: ["main", "transit", "virtual", "quarantine"] },
  { code: "inventory_movement_type", nameEn: "Inventory Movement Types", nameAr: "أنواع حركة المخزون", module: "inventory", valueCodes: ["receipt", "issue", "transfer_in", "transfer_out", "adjustment", "count", "opening"] },
  { code: "stock_adjustment_reason", nameEn: "Stock Adjustment Reasons", nameAr: "أسباب تسوية المخزون", module: "inventory", valueCodes: ["increase", "decrease", "revaluation", "damage", "loss", "expiry"] },
  // Human Resources
  { code: "employment_type", nameEn: "Employment Types", nameAr: "أنواع التوظيف", module: "hr", valueCodes: ["full_time", "part_time", "contract", "temporary", "intern"] },
  { code: "gender", nameEn: "Genders", nameAr: "الجنس", module: "hr", valueCodes: ["male", "female"] },
  { code: "marital_status", nameEn: "Marital Statuses", nameAr: "الحالة الاجتماعية", module: "hr", valueCodes: ["single", "married", "divorced", "widowed"] },
  { code: "employee_status", nameEn: "Employee Statuses", nameAr: "حالات الموظف", module: "hr", valueCodes: ["active", "on_leave", "resigned", "terminated"] },
  { code: "attendance_status", nameEn: "Attendance Statuses", nameAr: "حالات الحضور", module: "hr", valueCodes: ["present", "absent", "late", "on_leave", "holiday", "weekend"] },
  { code: "salary_component_type", nameEn: "Salary Component Types", nameAr: "أنواع مكونات الراتب", module: "hr", valueCodes: ["earning", "deduction"] },
  { code: "loan_type", nameEn: "Loan Types", nameAr: "أنواع القروض", module: "hr", valueCodes: ["personal", "housing", "car", "emergency"] },
  { code: "evaluation_rating", nameEn: "Evaluation Ratings", nameAr: "تقديرات التقييم", module: "hr", valueCodes: ["excellent", "good", "average", "poor"] },
  { code: "hr_document_type", nameEn: "HR Document Types", nameAr: "أنواع وثائق الموظفين", module: "hr", valueCodes: ["id_card", "passport", "visa", "certificate", "work_permit"] },
  // Legal Affairs
  { code: "legal_source_type", nameEn: "Legal Source Types", nameAr: "أنواع مصدر العقد", module: "legal", valueCodes: ["legal", "sales", "construction", "procurement", "employee", "customer", "reservation"] },
  { code: "legal_contract_status", nameEn: "Legal Contract Statuses", nameAr: "حالات العقد القانوني", module: "legal", valueCodes: ["draft", "under_review", "approved", "active", "suspended", "terminated", "expired", "renewed", "cancelled"] },
  { code: "legal_case_type", nameEn: "Legal Case Types", nameAr: "أنواع القضايا", module: "legal", valueCodes: ["civil", "commercial", "labor", "criminal", "administrative", "arbitration"] },
  { code: "legal_case_role", nameEn: "Legal Case Roles", nameAr: "أدوار القضية", module: "legal", valueCodes: ["plaintiff", "defendant", "third_party"] },
  { code: "legal_case_status", nameEn: "Legal Case Statuses", nameAr: "حالات القضية", module: "legal", valueCodes: ["open", "in_progress", "settled", "appealed", "closed"] },
  { code: "legal_hearing_status", nameEn: "Legal Hearing Statuses", nameAr: "حالات الجلسة", module: "legal", valueCodes: ["scheduled", "adjourned", "completed", "cancelled"] },
  { code: "legal_claim_type", nameEn: "Legal Claim Types", nameAr: "أنواع المطالبات", module: "legal", valueCodes: ["financial", "contractual", "damages"] },
  { code: "legal_claim_direction", nameEn: "Legal Claim Directions", nameAr: "اتجاه المطالبة", module: "legal", valueCodes: ["by_company", "against_company"] },
  { code: "legal_notice_type", nameEn: "Legal Notice Types", nameAr: "أنواع الإنذارات", module: "legal", valueCodes: ["warning", "demand", "termination"] },
  { code: "advisor_type", nameEn: "Advisor Types", nameAr: "أنواع المستشارين", module: "legal", valueCodes: ["internal", "external"] },
  // Unit Handover
  { code: "handover_type", nameEn: "Handover Types", nameAr: "أنواع التسليم", module: "handover", valueCodes: ["initial", "final"] },
  { code: "handover_status", nameEn: "Handover Statuses", nameAr: "حالات التسليم", module: "handover", valueCodes: ["requested", "scheduled", "rescheduled", "in_progress", "completed", "cancelled"] },
  // Customer Service
  { code: "service_request_type", nameEn: "Service Request Types", nameAr: "أنواع طلبات الخدمة", module: "customerService", valueCodes: ["complaint", "maintenance", "support"] },
  { code: "service_priority", nameEn: "Service Priorities", nameAr: "أولويات الخدمة", module: "customerService", valueCodes: ["low", "medium", "high", "urgent", "critical"] },
  // Fixed Assets
  { code: "asset_depreciation_method", nameEn: "Asset Depreciation Methods", nameAr: "طرق إهلاك الأصول", module: "fixedAssets", valueCodes: ["straight_line", "declining_balance"] },
  { code: "asset_status", nameEn: "Asset Statuses", nameAr: "حالات الأصول", module: "fixedAssets", valueCodes: ["active", "under_maintenance", "disposed", "written_off"] },
  { code: "asset_count_result", nameEn: "Asset Count Results", nameAr: "نتائج جرد الأصول", module: "fixedAssets", valueCodes: ["found", "missing", "damaged"] },
  { code: "asset_disposal_type", nameEn: "Asset Disposal Types", nameAr: "أنواع استبعاد الأصول", module: "fixedAssets", valueCodes: ["sale", "scrap", "donation", "write_off"] },
];

export function labelFor(code: string | null | undefined, lang: Lang): string {
  if (!code) return "-";
  const entry = LABELS[code];
  return entry ? entry[lang] : code;
}
